#!/bin/sh
set -e

export PATH=/opt/incus/bin/:${PATH}
export INCUS_OVMF_PATH=/opt/incus/share/qemu/
export LD_LIBRARY_PATH=/opt/incus/lib/
export INCUS_LXC_TEMPLATE_CONFIG=/opt/incus/share/lxc/config/

case "$1" in
    start)
      systemctl is-active incus -q && exit 0
      exec incusd activateifneeded
    ;;

    stop)
      systemctl is-active incus -q || exit 0
      exec incusd shutdown
    ;;

    *)
        echo "unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
