#!/bin/sh
set -e

export INCUS_LXC_HOOK=/opt/incus/share/lxc/hooks/
export INCUS_LXC_TEMPLATE_CONFIG=/opt/incus/share/lxc/config/
export INCUS_OVMF_PATH=/opt/incus/share/qemu/
export LD_LIBRARY_PATH=/opt/incus/lib/
export PATH=/opt/incus/bin/:${PATH}

exec incusd "$@"
