#!/bin/sh
set -e

case "$1" in
    install|upgrade)
        if ! getent group incus >/dev/null; then
            addgroup --system incus
        fi

        if ! getent group incus-admin >/dev/null; then
            addgroup --system incus-admin
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
