#!/bin/sh
set -e

case "$1" in
    configure)
        if [ -z "${2}" ]; then
            # Restart incus on initial installation to pick up the UI.
            if systemctl is-active incus.service -q; then
                systemctl restart incus.service
            fi
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
