name: Builds
on:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-incus:
    name: Build Incus
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-26.04
          - debian-12
          - debian-13
        arch:
          - amd64
          - arm64
    runs-on:
      - self-hosted
      - zabbly-incus-build
      - arch-${{ matrix.arch }}
      - image-${{ matrix.os }}

    env:
      OS_ARCH: ${{ matrix.arch }}
      OS_NAME: ${{ matrix.os }}
      PKG_CONFIG_PATH: "/opt/incus/lib/pkgconfig/"
      CGO_LDFLAGS: "-L/opt/incus/lib/"
      CGO_CFLAGS: "-I/opt/incus/include/"
      LD_LIBRARY_PATH: "/opt/incus/lib/"
      CPATH: "/opt/incus/include/"
      PATH: "/home/runner/.cargo/bin:/home/runner/.local/bin:/opt/incus/bin:/usr/local/go/bin:/usr/local/node/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

      # Linux Containers projects
      DISTROBUILDER_TAG: "distrobuilder-3.2"
      INCUS_COMPOSE_TAG: "v1.2.0"
      INCUS_TAG: "v7.3.0"
      INCUS_UI_CANONICAL_TAG: "incus-0.21.6"
      LXCFS_TAG: "v7.0.0"
      LXC_TAG: "v7.0.0"

      # External dependencies
      COWSQL_TAG: "v1.15.9"
      CRIU_TAG: "v4.2.1"
      EDK2_TAG: "edk2-stable202605"
      GOLANG_TAG: "go1.26.6"
      LEGO_TAG: "v4.35.2"
      LIBTPMS_TAG: "v0.10.2"
      LIBURING_TAG: "liburing-2.15"
      NASM_TAG: "nasm-2.16.03"
      NVIDIA_CONTAINER_TAG: "v1.20.0"
      QEMU_TAG: "v11.1.0"
      RAFT_TAG: "v0.22.1"
      SEABIOS_TAG: "rel-1.17.0"
      SKOPEO_TAG: "v1.24.0"
      SWTPM_TAG: "v0.10.1"
      TRUENAS_INCUS_CTL_TAG: "v0.7.7"
      VIRGLRENDERER_TAG: "1.3.0"
      VIRTIOFSD_TAG: "v1.14.0"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config --global --add advice.detachedHead false
          git config --global user.email "noreply@zabbly.com"
          git config --global user.name "Zabbly Incus build"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes \
            acpica-tools \
            asciidoc \
            autoconf \
            automake \
            bison \
            bmake \
            build-essential \
            curl \
            debhelper \
            devscripts \
            dosfstools \
            expect \
            flex \
            gawk \
            gettext \
            gnutls-bin \
            gnutls-dev \
            git \
            iproute2 \
            libacl1-dev \
            libaio-dev \
            libapparmor-dev \
            libbtrfs-dev \
            libcap-dev \
            libcap-ng-dev \
            libdbus-1-dev \
            libdevmapper-dev \
            libelf-dev \
            libfuse3-dev \
            libglib2.0-dev \
            libgnutls28-dev \
            libgpgme-dev \
            libjson-glib-dev \
            libnet1-dev \
            libnl-3-dev \
            libnuma-dev \
            libpam0g-dev \
            libpixman-1-dev \
            libpng-dev \
            libprotobuf-c-dev \
            libprotobuf-dev \
            librbd-dev \
            libseccomp-dev \
            libselinux1-dev \
            libspice-server-dev \
            libsqlite3-dev \
            libssl-dev \
            libsystemd-dev \
            libtirpc-dev \
            libtool \
            libudev-dev \
            libusb-1.0-0-dev \
            libusbredirhost-dev \
            libuv1-dev \
            lsb-release \
            mtools \
            ninja-build \
            pipx \
            pkg-config \
            protobuf-c-compiler \
            protobuf-compiler \
            python3-cryptography \
            python3-jinja2 \
            python3-pexpect \
            python3-pip \
            python3-setuptools \
            python3-tomli \
            python3-venv \
            rsync \
            socat \
            uuid-dev \
            xmlto \
            xorriso

          if [ "${OS_NAME}" = "debian-13" ] || [ "${OS_NAME}" = "ubuntu-26.04" ]; then
            sudo apt-get install --no-install-recommends --yes \
                libdrm-dev \
                libegl1-mesa-dev \
                libgbm-dev \
                libepoxy-dev
          fi

          sudo apt-get install --no-install-recommends --yes systemd-dev || true

          pipx install meson

      - name: Install Go
        run: |
          curl -sL "https://go.dev/dl/${GOLANG_TAG}.linux-${OS_ARCH}.tar.gz" | sudo tar -C /usr/local/ -zx
          go version

      - name: Install Rust
        run: |
          curl -sL https://sh.rustup.rs -o install-rust.sh
          bash install-rust.sh -y

      - name: Install Node
        run: |
          [ "${OS_ARCH}" = "amd64" ] && NODE_ARCH=x64
          [ "${OS_ARCH}" = "arm64" ] && NODE_ARCH=arm64


          sudo mkdir /usr/local/node/
          curl -sL "https://nodejs.org/dist/v24.18.0/node-v24.18.0-linux-${NODE_ARCH}.tar.xz" | sudo tar -C /usr/local/node/ -Jx --strip-components=1

      - name: Build environment
        run: |
          sudo mkdir -p /build/ /opt/
          sudo chown $(id -u):$(id -g) /build/ /opt/

          mkdir -p \
            /opt/incus/bin/ \
            /opt/incus/include/ \
            /opt/incus/lib/ \
            /opt/incus/lib/systemd \
            /opt/incus/share/

      - name: Get the code
        run: |
          git clone https://github.com/lxc/distrobuilder /build/distrobuilder --depth 1 -b "${DISTROBUILDER_TAG}"
          git clone https://github.com/lxc/lxc /build/lxc -b "${LXC_TAG}"
          git clone https://github.com/lxc/lxcfs /build/lxcfs --depth 1 -b "${LXCFS_TAG}"
          git clone https://github.com/lxc/incus /build/incus -b "${INCUS_TAG}"
          git clone https://github.com/lxc/incus-compose /build/incus-compose --depth 1 -b "${INCUS_COMPOSE_TAG}"
          git clone https://github.com/zabbly/incus-ui-canonical /build/incus-ui-canonical --depth 1 -b "${INCUS_UI_CANONICAL_TAG}"

          git clone https://github.com/axboe/liburing /build/liburing --depth 1 -b "${LIBURING_TAG}"
          git clone https://github.com/checkpoint-restore/criu /build/criu --depth 1 -b "${CRIU_TAG}"
          git clone https://github.com/containers/skopeo /build/skopeo --depth 1 -b "${SKOPEO_TAG}"
          git clone https://github.com/cowsql/cowsql /build/cowsql --depth 1 -b "${COWSQL_TAG}"
          git clone https://github.com/cowsql/raft /build/raft --depth 1 -b "${RAFT_TAG}"
          git clone https://github.com/go-acme/lego /build/lego --depth 1 -b "${LEGO_TAG}"
          git clone https://github.com/NVIDIA/libnvidia-container /build/libnvidia-container --depth 1 -b "${NVIDIA_CONTAINER_TAG}"
          git clone https://github.com/stefanberger/libtpms /build/libtpms --depth 1 -b "${LIBTPMS_TAG}"
          git clone https://github.com/stefanberger/swtpm /build/swtpm --depth 1 -b "${SWTPM_TAG}"
          git clone https://github.com/tianocore/edk2 /build/edk2 --recurse-submodules --shallow-submodules --depth 1 -b "${EDK2_TAG}"
          git clone https://github.com/truenas/truenas_incus_ctl /build/truenas_incus_ctl --depth 1 -b "${TRUENAS_INCUS_CTL_TAG}"
          git clone https://gitlab.com/qemu-project/qemu /build/qemu --depth 1 -b "${QEMU_TAG}"
          git clone https://gitlab.com/qemu-project/seabios /build/seabios --depth 1 -b "${SEABIOS_TAG}"
          git clone https://gitlab.com/virtio-fs/virtiofsd /build/virtiofsd --depth 1 -b "${VIRTIOFSD_TAG}"

          if [ "${OS_NAME}" = "debian-13" ] || [ "${OS_NAME}" = "ubuntu-26.04" ]; then
            git clone https://gitlab.freedesktop.org/virgl/virglrenderer /build/virglrenderer --depth 1 -b "${VIRGLRENDERER_TAG}"
          fi

          mkdir /build/nasm/
          curl -sL "https://www.nasm.us/pub/nasm/releasebuilds/$(echo ${NASM_TAG} | cut -d- -f2)/${NASM_TAG}.tar.gz" --resolve www.nasm.us:443:198.137.202.136 | tar -C /build/nasm/ -zx --strip-components=1

      - name: Build liburing
        run: |
          cd /build/liburing
          ./configure --prefix=/opt/incus
          make

          mkdir -p /build/target/liburing/
          DESTDIR=/build/target/liburing make install
          rsync -a /build/target/liburing/opt/incus/include/* /opt/incus/include/
          rsync -a /build/target/liburing/opt/incus/lib/* /opt/incus/lib/

      - name: Build raft
        run: |
          cd /build/raft
          autoreconf -i
          ./configure --prefix=/opt/incus
          make

          mkdir -p /build/target/raft/
          DESTDIR=/build/target/raft/ make install
          rsync -a /build/target/raft/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/raft/opt/incus/lib/ /opt/incus/lib/

      - name: Build cowsql
        run: |
          REPO="${PWD}"

          cd /build/cowsql
          patch -p1 < "${REPO}/patches/cowsql-0001-discarded-qualifiers.patch"

          autoreconf -i
          ./configure --prefix=/opt/incus
          make

          mkdir -p /build/target/cowsql/
          DESTDIR=/build/target/cowsql/ make install
          rsync -a /build/target/cowsql/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/cowsql/opt/incus/lib/ /opt/incus/lib/

      - name: Build LXC
        run: |
          REPO="${PWD}"

          cd /build/lxc

          meson setup build \
                  --prefix=/opt/incus \
                  --libdir=/opt/incus/lib \
                  -Dexamples=false \
                  -Dman=false \
                  -Dtools=false \
                  -Dtests=false \
                  -Dmemfd-rexec=false \
                  -Dapparmor=true \
                  -Dseccomp=true \
                  -Dselinux=true \
                  -Dcapabilities=true \
                  -Dio-uring-event-loop=false
          meson compile -C build

          mkdir -p /build/target/lxc/
          DESTDIR=/build/target/lxc/ meson install -C build
          rsync -a /build/target/lxc/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/lxc/opt/incus/lib/ /opt/incus/lib/
          mkdir -p /opt/incus/share/lxc/config/common.conf.d/
          mkdir -p /opt/incus/share/lxc/hooks/
          cp /build/target/lxc/opt/incus/share/lxc/hooks/nvidia /opt/incus/share/lxc/hooks/

      - name: Build LXCFS
        run: |
          REPO="${PWD}"

          cd /build/lxcfs
          meson setup build \
                  --prefix=/opt/incus \
                  --libdir=/opt/incus/lib \
                  -Ddocs=false \
                  -Dtests=false
          meson compile -C build

          mkdir -p /build/target/lxcfs/
          DESTDIR=/build/target/lxcfs/ meson install -C build
          rsync -a /build/target/lxcfs/opt/incus/bin/ /opt/incus/bin/
          rsync -a /build/target/lxcfs/opt/incus/share/ /opt/incus/share/
          rsync -a /build/target/lxcfs/opt/incus/lib/ /opt/incus/lib/

          sed -i "s#/var/lib/lxcfs#/var/lib/incus-lxcfs#g" /opt/incus/share/lxcfs/lxc.mount.hook
          patch -p1 /opt/incus/share/lxcfs/lxc.mount.hook < "${REPO}/patches/lxcfs-0001-hook.patch"

      - name: Build Incus
        run: |
          REPO="${PWD}"

          cd /build/incus

          git cherry-pick b406a0397cc3a7778c79dbf863e3559b38d34353  # incus/low-level: Fix naming inconsistency
          git cherry-pick a2aa861daec6d4539bdfd5c519416b9b08bc87ec  # i18n: Update translation templates
          git cherry-pick 19269185635ab4470de60ef1c828a43a13ed0fe4  # shared/api: Hide additional sensitive config keys
          git cherry-pick 66e092f0fff264066b2754f3f16b1bcb2c7c7cba  # incusd/instance/qmp: Bump query-migrate timeout
          git cherry-pick 54d230183cde6f5d7e996e1b1b488ddcf6929bfc  # incusd/db: Have NetworkNodeConfigs only consider the requested network
          git cherry-pick 066ef03eb91f2a2450d256aa70b3857dbfa6b69c  # incusd/network/ovn: Skip empty transactions in SetChassisGroupPriority
          git cherry-pick 28c287796fce2e5488873a633ae8bb1b3ef5e97a  # docs: Clarify the sentence about Incus owning the ZFS pool/dataset
          git cherry-pick 11a82f81ce9f2b5a8ea74c668a33b8eb82f7f90e  # incusd/daemon: Drop else branches in project expansion
          git cherry-pick 59a71850fbce8df07bff8057138e2f9e690ee2b0  # incusd/bgp: Resolve neighbor address for unnumbered peers
          git cherry-pick 6c9ac20100b3b5da3926f544c2577ba5ef9c2edc  # incus/remote: Restrict proxy /1.0 cache to GET and invalidate on changes
          git cherry-pick 69b0915fdd9e8ea5fe27fc69b3e21c1e61438d4b  # incusd/endpoints: Fix proxy protocol handling
          git cherry-pick 07f8dae5fd83b9496579b3bcbb9c07d77155a911  # incusd/storage: Unmount leftover mounts in CleanupInstancePaths
          git cherry-pick cf1cf59f5b0b6fcf16261892825d1a211c18b30c  # incusd/device: Check interface isn't in use by host before passthrough
          git cherry-pick 14f676ab8851f457d7c840f2774b62d33e97ef70  # incusd/instance/lxc: Fix mount options of OCI /run tmpfs
          git cherry-pick 3a7ddebe4f2c4558d880f815f85c282ad192593f  # incusd/instance/lxc: Skip OCI /run tmpfs when image populates /run
          git cherry-pick d8fecc63932678d06cbf6d0bba765492bd920755  # incusd/cluster: Stop instances in place when evacuation has no target
          git cherry-pick 25f04611b258785c285134818573252bf184ded4  # incusd/forknet: Fix concurrent DHCP resolv.conf handling
          git cherry-pick bc57bb2385562d71bf3c77c9a8d6b16b12e3d908  # incusd/instance: Update oci.dns.* descriptions
          git cherry-pick 00779baa2bfaef57fcd84477bf5f08d58607ad3a  # doc: Update config
          git cherry-pick 72fe048beda95dc3d4a982be4c09321eb392aa18  # incusd/instance/lxc: Enable edns0 in OCI resolv.conf
          git cherry-pick 69f1bc89f502f7a7f3670b32027478915bb6df4e  # incusd/forknet: Enable edns0 in resolv.conf
          git cherry-pick 8fb121b80f5e6127ee31814d576726a0c85e133b  # shared/uefi: Various device path fixes
          git cherry-pick a80638e0dad73e8f0c426c200eba26e57dd1db5e  # client: use a copy of ProtocolIncus for WithContext
          git cherry-pick b7518d67e16083576a96bfed9ef238032277cb83  # client: Preserve tempPath in UseProject and UseTarget
          git cherry-pick afa4ace07c6ced8faa34d81823b31cd9dd299bd9  # incusd/network/ovn: Replace stale SNAT rule on external address change
          git cherry-pick c12e33b3920fcc43dc411f93d0abd1d4f9a33acf  # incusd/device/nic_ovn: Allow live update of ipv4/ipv6.address.external
          git cherry-pick a7413d3683fdf376420b552c255e8cd936167493  # incusd/db: Add generated network, network_config and network_node entities
          git cherry-pick 4d88b649c8e265308fd13a4e6c64f5f4c54ecd4d  # incusd/db: Add GetCreatedNetworksInfo
          git cherry-pick b9432175eee9d98d9ef6d54bd44b42db65e105b4  # incusd/network: Add LoadAllCreated
          git cherry-pick 8bec5dccbac60e71dd1a5e7b2b05b110fa5870b0  # incusd/network: Reduce database queries in OVN network startup
          git cherry-pick a07c9691b1034a01768d7a22f954c21c75861e88  # incusd/networks: Reduce database queries during network startup
          git cherry-pick b7d9906444711c78009558c01f8d63e551c87e61  # incusd: Use cached server name for warning operations
          git cherry-pick abd0a91dbe165e33536c1171a288bef7848a3ce6  # incusd/cluster: Add ConnectIfBucketIsRemote
          git cherry-pick d75bfe188b91f16dfc6ba7bd8cf02018d952d925  # incusd: Add forwardedResponseIfBucketIsRemote
          git cherry-pick 461065f4c4a04ad29299b7cd82be49b4c8142635  # incusd: Forward storage bucket requests to the cluster member holding the bucket
          git cherry-pick f586fb3bf9e0236b9510efcb6750fca24d1968d1  # doc: Document storage bucket handling in clusters
          git cherry-pick d54cc569933aaa1f8580c5a349b35d31757b37fb  # internal/migration: Don't double close websocket writer
          git cherry-pick 6afcb63368432afd33899ecd020c2363fff353e7  # incusd/instance/qmp: Ignore timeouts during migration
          git cherry-pick 012947c0b3f1fbb233bf29d57d5dfe7ebe9b1be1  # incusd/network/ovn: Don't replace DNAT rules sharing a logical IP
          git cherry-pick 47cbc0b34fdd7d6b60a40a76d73b493269a8a881  # incusd/network/ovn: Use tag_request on nested switch ports
          git cherry-pick 640c238d9ca7b24ddb4920084a1b6ce2bdae263c  # client: Handle unmanaged networks in preseed
          git cherry-pick c85d5bf2133bb94aa5764d254a032f5a157ccfa8  # incusd/storage/lvm: Wipe source device rather than VG name
          git cherry-pick 6ad6b511d195b307fa2da3168d69de72313ca92c  # client: Detect dead event connections
          git cherry-pick 5ffcc4da289f76a38e619008bb034b108a4ab7ee  # incusd/events: Deliver events in order
          git cherry-pick 325f06901d57d24845811bb8530e4f7a0e430e1d  # incusd/projects: Send project-updated after the update
          git cherry-pick e108b7bae9b3741b625e1b0157b33e062437de37  # doc: Document event ordering
          git cherry-pick f133589810388252226ee53202500534788e04d1  # client: Fix Disconnect not disconnecting
          git cherry-pick d39077c5f8df9520aad6d7fae5e7be3e4fa3af7c  # incusd/storage/lvm: Detect block type in ListVolumes
          git cherry-pick efae9443acbc29d79d118cd740eb23e221dcf020  # incusd/storage: Tolerate missing snapshot record on delete
          git cherry-pick b3515a114c11d1f148d3cee932293e1f86ec8abb  # incusd/storage: Repair snapshot records on refresh
          git cherry-pick 84fa06c36981d34cd2b585b171a9ddc5a64c7113  # incus/admin_sql: Fix integer rendering
          git cherry-pick be668c751664d69f20e8358ba9cd7f04ebec5a4c  # incusd/instance/qemu: Use temporary data-file when growing metadata image

          go build -o "/opt/incus/bin/fuidshift" github.com/lxc/incus/v7/cmd/fuidshift
          go build -o "/opt/incus/bin/incus" github.com/lxc/incus/v7/cmd/incus
          go build -o "/opt/incus/bin/incus-benchmark" github.com/lxc/incus/v7/cmd/incus-benchmark
          go build -o "/opt/incus/bin/incus-migrate" github.com/lxc/incus/v7/cmd/incus-migrate
          go build -o "/opt/incus/bin/incus-simplestreams" github.com/lxc/incus/v7/cmd/incus-simplestreams
          go build -o "/opt/incus/bin/incus-user" github.com/lxc/incus/v7/cmd/incus-user
          go build -o "/opt/incus/bin/incusd" -tags=libsqlite3 github.com/lxc/incus/v7/cmd/incusd
          go build -o "/opt/incus/bin/lxc-to-incus" github.com/lxc/incus/v7/cmd/lxc-to-incus

          mkdir -p /opt/incus/agent
          if [ "$(uname -m)" = "x86_64" ]; then
              GOARCH=amd64 GOOS=darwin CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.macos.x86_64" -tags=agent,netgo github.com/lxc/incus/v7/cmd/incus-agent

              GOARCH=amd64 GOOS=freebsd CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.freebsd.x86_64" -tags=agent,netgo github.com/lxc/incus/v7/cmd/incus-agent
              GOARCH=386 GOOS=freebsd CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.freebsd.i686" -tags=agent,netgo github.com/lxc/incus/v7/cmd/incus-agent

              GOARCH=amd64 CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.linux.x86_64" -tags=agent,netgo github.com/lxc/incus/v7/cmd/incus-agent
              GOARCH=386 CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.linux.i686" -tags=agent,netgo github.com/lxc/incus/v7/cmd/incus-agent

              GOARCH=amd64 GOOS=windows CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.windows.x86_64" -tags=agent,netgo github.com/lxc/incus/v7/cmd/incus-agent
              GOARCH=386 GOOS=windows CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.windows.i686" -tags=agent,netgo github.com/lxc/incus/v7/cmd/incus-agent
          elif [ "$(uname -m)" = "aarch64" ]; then
              GOARCH=arm64 GOOS=darwin CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.macos.aarch64" -tags=agent,netgo github.com/lxc/incus/v7/cmd/incus-agent
              GOARCH=amd64 GOOS=freebsd CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.freebsd.aarch64" -tags=agent,netgo github.com/lxc/incus/v7/cmd/incus-agent
              GOARCH=arm64 CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.linux.aarch64" -tags=agent,netgo github.com/lxc/incus/v7/cmd/incus-agent
              GOARCH=arm64 GOOS=windows CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.windows.aarch64" -tags=agent,netgo github.com/lxc/incus/v7/cmd/incus-agent
          fi

          make build-mo
          mkdir -p /opt/incus/share/locale
          cp po/*.mo /opt/incus/share/locale/

          make doc
          cp -R doc/html /opt/incus/doc

          mkdir -p /opt/incus/share/completions/
          /opt/incus/bin/incus completion bash > /opt/incus/share/completions/bash
          /opt/incus/bin/incus completion fish > /opt/incus/share/completions/fish
          /opt/incus/bin/incus completion zsh > /opt/incus/share/completions/zsh

      - name: Build UI (canonical)
        run: |
          REPO="${PWD}"

          cd /build/incus-ui-canonical

          # Complete re-branding.
          find -type f -name "*.ts" -o -name "*.tsx" -o -name "*.scss" | xargs sed -i -f "${REPO}/patches/ui-canonical-renames.sed"

          npm install -g --prefix /home/runner/.local yarn
          yarn install
          yarn build

          mkdir -p /opt/incus/ui-canonical/
          rsync -a /build/incus-ui-canonical/build/ui/ /opt/incus/ui-canonical/

      - name: Build Distrobuilder
        run: |
          cd /build/distrobuilder
          go build -o "/opt/incus/bin/distrobuilder" github.com/lxc/distrobuilder/distrobuilder

      - name: Build Incus Compose
        run: |
          cd /build/incus-compose
          go build -ldflags="-w -s -X github.com/lxc/incus-compose/cmd/incus-compose/version.Version=${INCUS_COMPOSE_TAG}" -o "/opt/incus/bin/incus-compose" github.com/lxc/incus-compose/cmd/incus-compose

      - name: Build CRIU
        run: |
          REPO="${PWD}"

          cd /build/criu

          make WERROR=0
          cp criu/criu /opt/incus/bin/

      - name: Build libnvidia-container
        run: |
          REPO="${PWD}"

          cd /build/libnvidia-container
          patch -p1 < "${REPO}/patches/nvidia-0001-Fix-for-22.04-build.patch"
          patch -p1 < "${REPO}/patches/nvidia-0002-pre-load-libdl.patch"
          make prefix=/

          mkdir /build/target/libnvidia-container
          DESTDIR=/build/target/libnvidia-container make install prefix=/
          rsync -a /build/target/libnvidia-container/bin/ /opt/incus/bin/
          rsync -a /build/target/libnvidia-container/include/ /opt/incus/include/
          rsync -a /build/target/libnvidia-container/lib/ /opt/incus/lib/

      - name: Build seabios
        if: ${{ matrix.arch == 'amd64' }}
        run: |
          REPO="${PWD}"

          cd /build/seabios

          # Build a traditional seabios.
          make clean distclean
          echo "CONFIG_QEMU=y" > .config
          echo "CONFIG_QEMU_HARDWARE=y" >> .config
          echo "CONFIG_BOOTSPLASH=n" >> .config
          echo "CONFIG_ROM_SIZE=256" >> .config
          echo "CONFIG_XEN=n" >> .config
          echo "CONFIG_PVSCSI=n" >> .config
          echo "CONFIG_ESP_SCSI=n" >> .config
          echo "CONFIG_LSI_SCSI=n" >> .config
          echo "CONFIG_MEGASAS=n" >> .config
          echo "CONFIG_MPT_SCSI=n" >> .config
          echo "CONFIG_FLOPPY=n" >> .config
          echo "CONFIG_FLASH_FLOPPY=n" >> .config
          make oldnoconfig V=1
          make V=1 PYTHON=python3

          mkdir -p /opt/incus/share/qemu/
          cp out/bios.bin /opt/incus/share/qemu/seabios.bin

      - name: Build nasm
        run: |
          REPO="${PWD}"

          cd /build/nasm
          patch -p1 < "${REPO}/patches/nasm-0000-disable-manpages.patch"
          ./configure --prefix=/opt/incus
          make

          mkdir -p /build/target/nasm/
          DESTDIR=/build/target/nasm make install
          rsync -a /build/target/nasm/opt/incus/bin/ /opt/incus/bin/

      - name: Build EDK2
        run: |
          REPO="${PWD}"

          cd /build/edk2
          patch -p1 < "${REPO}/patches/edk2-0001-force-DUID-LLT.patch"
          cp "${REPO}/patches/edk2-0002-logo.bmp" MdeModulePkg/Logo/Logo.bmp
          patch -p1 < "${REPO}/patches/edk2-0003-boot-delay.patch"
          patch -p1 < "${REPO}/patches/edk2-0004-gcc-errors.patch"
          patch -p1 < "${REPO}/patches/edk2-0005-Revert-ArmVirtPkg-make-EFI_LOADER_DATA-non-executabl.patch"
          patch -p1 < "${REPO}/patches/edk2-0006-disable-EFI-memory-attributes-protocol.patch"
          patch -p1 < "${REPO}/patches/edk2-0007-OvmfPkg-X64-add-opt-org-tianocore-UninstallMemAttrProtocol-support.patch"
          patch -p1 < "${REPO}/patches/edk2-0008-Disable-virtio-keyboard.patch"
          patch -p1 < "${REPO}/patches/edk2-9999-disable-UEFI-shell-under-SecureBoot.patch"

          sed -i "s#02/02/2022#$(date +%m/%d/%Y)#g" OvmfPkg/SmbiosPlatformDxe/SmbiosPlatformDxe.c

          EDK2_ARCH="X64"
          EDK2_PKG="OvmfPkg/OvmfPkgX64.dsc"
          EDK2_FV_CODE="OVMF_CODE"
          EDK2_FV_VARS="OVMF_VARS"
          if [ "$(uname -m)" = "aarch64" ]; then
              EDK2_ARCH="AARCH64"
              EDK2_PKG="ArmVirtPkg/ArmVirtQemu.dsc"
              EDK2_FV_CODE="QEMU_EFI"
              EDK2_FV_VARS="QEMU_VARS"
          fi

          build_edk2() {
              TARGET_CODE="$1"
              shift
              TARGET_VARS="$1"
              shift

              set -ex
              (
              cat << EOF
                  . ./edksetup.sh
                  make -C BaseTools ARCH=${EDK2_ARCH}
                  build -a ${EDK2_ARCH} -t GCC -b RELEASE -p ${EDK2_PKG} \
                    -DSMM_REQUIRE=TRUE \
                    -DSECURE_BOOT_ENABLE=TRUE \
                    -DNETWORK_IP4_ENABLE=TRUE \
                    -DNETWORK_IP6_ENABLE=TRUE \
                    -DNETWORK_TLS_ENABLE=TRUE \
                    -DNETWORK_HTTP_BOOT_ENABLE=TRUE \
                    -DTPM2_ENABLE=TRUE \
                    -DTPM2_CONFIG_ENABLE=TRUE \
                    --pcd PcdUninstallMemAttrProtocol=TRUE \
                    $@
          EOF
              ) | bash -e

              cp Build/*/*/FV/${EDK2_FV_CODE}.fd "${TARGET_CODE}"
              cp Build/*/*/FV/${EDK2_FV_VARS}.fd "${TARGET_VARS}"

              if [ "$(uname -m)" = "aarch64" ]; then
                  truncate -s 64m "${TARGET_CODE}"
                  truncate -s 64m "${TARGET_VARS}"
              fi
          }

          mkdir -p "/opt/incus/share/qemu/"
          build_edk2 \
            "/opt/incus/share/qemu/OVMF_CODE.4MB.fd" \
            "/opt/incus/share/qemu/OVMF_VARS.4MB.fd" \
            -DFD_SIZE_4MB

          ln -s OVMF_CODE.4MB.fd /opt/incus/share/qemu/OVMF_CODE.fd
          ln -s OVMF_VARS.4MB.fd /opt/incus/share/qemu/OVMF_VARS.fd

          # Unified (embedded variable store) firmware for AMD SEV.
          if [ "${EDK2_ARCH}" = "X64" ]; then
              touch OvmfPkg/AmdSev/Grub/grub.efi

              (
              cat << EOF
                  . ./edksetup.sh
                  build -a X64 -t GCC -b RELEASE -p OvmfPkg/AmdSev/AmdSevX64.dsc \
                    -DCC_MEASUREMENT_ENABLE=TRUE \
                    -DNETWORK_IP4_ENABLE=TRUE \
                    -DNETWORK_IP6_ENABLE=TRUE \
                    -DNETWORK_TLS_ENABLE=TRUE \
                    -DNETWORK_HTTP_BOOT_ENABLE=TRUE \
                    -DTPM2_ENABLE=TRUE
          EOF
              ) | bash -e

              cp Build/AmdSev/*/FV/OVMF.fd /opt/incus/share/qemu/OVMF.amdsev.fd
          fi

      - name: Build libtpms
        run: |
          REPO="${PWD}"

          cd /build/libtpms
          patch -p1 < "${REPO}/patches/libtpms-0001-Fix-a-compilation-error-in-TPMLIB_GetPlaintext.patch"

          ./autogen.sh
          ./configure --prefix=/opt/incus --with-tpm2 --with-openssl
          make

          mkdir -p /build/target/libtpms/
          DESTDIR=/build/target/libtpms make install
          rsync -a /build/target/libtpms/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/libtpms/opt/incus/lib/ /opt/incus/lib/

      - name: Build swtpm
        run: |
          cd /build/swtpm
          ./autogen.sh
          ./configure --prefix=/opt/incus --with-gnutls --with-seccomp --with-openssl --without-cuse
          make

          mkdir -p /build/target/swtpm/
          DESTDIR=/build/target/swtpm make install
          rsync -a /build/target/swtpm/opt/incus/bin/ /opt/incus/bin/
          rsync -a /build/target/swtpm/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/swtpm/opt/incus/lib/ /opt/incus/lib/

          mkdir -p /opt/incus/etc/
          cat > /opt/incus/etc/swtpm-localca.options << EOF
          --platform-manufacturer Incus
          --platform-version 2.1
          --platform-model QEMU
          EOF

      - name: Build virtiofsd
        run: |
          cd /build/virtiofsd
          cargo build --release
          cp target/release/virtiofsd /opt/incus/bin/

      - name: Build lego
        run: |
          cd /build/lego
          go build -o "/opt/incus/bin/lego" github.com/go-acme/lego/v4/cmd/lego

      - name: Build skopeo
        run: |
          cd /build/skopeo
          go build -o "/opt/incus/bin/skopeo" ./cmd/skopeo

      - name: Build TrueNAS Incus CTL
        run: |
          REPO="${PWD}"

          cd /build/truenas_incus_ctl

          patch -p1 < "${REPO}/patches/truenas-0001-bump-timeouts.patch"

          go build -o "/opt/incus/bin/truenas_incus_ctl" truenas/truenas_incus_ctl

      - name: Build virglrenderer
        if: ${{ matrix.os == 'debian-13' || matrix.os == 'ubuntu-26.04' }}
        run: |
          cd /build/virglrenderer

          meson setup build \
                  --prefix=/opt/incus \
                  --libdir=/opt/incus/lib \
                  -Dplatforms=egl \
                  -Ddrm-renderers=amdgpu-experimental,asahi,msm,panfrost-experimental,i915-experimental
          meson compile -C build

          mkdir -p /build/target/virglrenderer/
          DESTDIR=/build/target/virglrenderer/ meson install -C build
          rsync -a /build/target/virglrenderer/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/virglrenderer/opt/incus/lib/ /opt/incus/lib/

      - name: Build QEMU
        run: |
          REPO="${PWD}"

          cd /build/qemu

          sed -i "s/^unset target_list$/target_list=\"$(uname -m)-softmmu\"/" configure

          sed -i "/subdir('tests')/d" meson.build

          opengl=""
          if [ "${OS_NAME}" = "debian-13" ] || [ "${OS_NAME}" = "ubuntu-26.04" ]; then
            opengl="--enable-opengl --enable-virglrenderer"
          fi

          ./configure \
                  --prefix=/opt/incus \
                  --libexecdir=bin \
                  --libdir=lib \
                  --disable-bochs \
                  --disable-cloop \
                  --disable-dmg \
                  --disable-docs  \
                  --disable-fuse  \
                  --disable-guest-agent \
                  --disable-parallels \
                  --disable-qed \
                  --disable-slirp \
                  --disable-user \
                  --disable-vdi \
                  --disable-vnc \
                  --disable-xen \
                  --disable-install-blobs \
                  --enable-attr \
                  --enable-cap-ng \
                  --enable-kvm \
                  --enable-libusb \
                  --enable-usb-redir \
                  --enable-linux-aio \
                  --enable-linux-io-uring \
                  --enable-numa \
                  --enable-pie \
                  --enable-png \
                  --enable-rbd \
                  --enable-seccomp \
                  --enable-spice \
                  --enable-system \
                  --enable-tcg \
                  --enable-tools \
                  --enable-vhost-crypto \
                  --enable-vhost-kernel \
                  --enable-vhost-net \
                  --enable-vhost-user \
                  --enable-virtfs \
                  ${opengl}
          make

          mkdir /build/target/qemu/
          DESTDIR=/build/target/qemu/ make install
          rsync -a /build/target/qemu/opt/incus/bin/ /opt/incus/bin/
          rsync -a /build/target/qemu/opt/incus/lib/ /opt/incus/lib/
          rsync -a /build/target/qemu/opt/incus/share/qemu/ /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/kvmvapic.bin /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/vgabios-qxl.bin /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/vgabios-virtio.bin /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/efi-e1000e.rom /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/efi-virtio.rom /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/efi-vmxnet3.rom /opt/incus/share/qemu/

      - name: Build Secure Boot firmware
        run: |
          REPO="${PWD}"

          cd /build/edk2

          FIRMWARE="OVMF"
          if [ "$(uname -m)" = "aarch64" ]; then
            FIRMWARE="AAVMF"
          fi

          cd "${REPO}/edk2-vars-generator"
          ./edk2-vars-generator -f "${FIRMWARE}" \
            -e /build/edk2/Build/*/*/*/EnrollDefaultKeys.efi \
            -s /build/edk2/Build/*/*/*/Shell.efi \
            -c "/opt/incus/share/qemu/OVMF_CODE.4MB.fd" \
            -V "/opt/incus/share/qemu/OVMF_VARS.4MB.fd" \
            -C "$(cat ${REPO}/zabbly-sb.oem.crt)" \
            -o "/opt/incus/share/qemu/OVMF_VARS.4MB.ms.fd"

      - name: Strip and cleanup binaries
        run: |
          rm -Rf /opt/incus/lib/debug/
          rm -Rf /opt/incus/include/
          rm -Rf /opt/incus/lib/pkgconfig/
          rm /opt/incus/lib/*.a /opt/incus/lib/*.la /opt/incus/lib/*/*.a /opt/incus/lib/*/*.la

          rm /opt/incus/bin/nasm
          rm /opt/incus/bin/ndisasm
          rm /opt/incus/bin/qemu-bridge-helper
          rm /opt/incus/bin/qemu-edid
          rm /opt/incus/bin/qemu-io
          rm /opt/incus/bin/qemu-pr-helper
          rm /opt/incus/bin/qemu-storage-daemon
          rm /opt/incus/share/qemu/trace-events-all

          strip /opt/incus/agent/*linux*
          strip /opt/incus/bin/*
          strip /opt/incus/lib/*so*

      - name: Make a Debian package
        env:
          PKGOS: ${{ matrix.os }}
        run: |
          [ "${PKGOS}" = "debian-12" ] && CODENAME=bookworm
          [ "${PKGOS}" = "debian-13" ] && CODENAME=trixie
          [ "${PKGOS}" = "ubuntu-22.04" ] && CODENAME=jammy
          [ "${PKGOS}" = "ubuntu-24.04" ] && CODENAME=noble
          [ "${PKGOS}" = "ubuntu-26.04" ] && CODENAME=resolute

          mkdir -p \
            pkg/ \
            pkg/etc \
            pkg/lib/systemd/system/ \
            pkg/opt/ \
            pkg/usr/bin/ \
            pkg/usr/lib/sysctl.d/ \
            pkg/usr/share/bash-completion/completions/ \
            pkg/usr/share/fish/vendor_completions.d/ \
            pkg/usr/share/zsh/vendor-completions/

          cp -R debian pkg/debian
          cp -R bin/* pkg/usr/bin/
          cp -R /opt/incus pkg/opt/
          cp -R etc/* pkg/etc/

          cp -R systemd/system/* pkg/lib/systemd/system/
          cp -R systemd/wrappers/* pkg/opt/incus/lib/systemd/
          cp -R systemd/sysctl.d/* pkg/usr/lib/sysctl.d/

          ln -s /opt/incus/share/completions/bash pkg/usr/share/bash-completion/completions/incus
          ln -s /opt/incus/share/completions/fish pkg/usr/share/fish/vendor_completions.d/incus.fish
          ln -s /opt/incus/share/completions/zsh pkg/usr/share/zsh/vendor-completions/_incus

          ln -s /opt/incus/bin/fuidshift pkg/usr/bin/fuidshift
          ln -s /opt/incus/bin/incus-simplestreams pkg/usr/bin/incus-simplestreams
          ln -s /opt/incus/bin/incus-benchmark pkg/usr/bin/incus-benchmark

          mkdir -p pkg/var/lib/incus
          chmod 711 pkg/var/lib/incus

          mkdir -p pkg/var/log/incus
          chmod 700 pkg/var/log/incus

          mkdir -p pkg/usr/share/locale
          for i in /opt/incus/share/locale/*.mo; do
            LANG=$(echo $i | sed -e "s#.*/locale/##g" -e "s#.mo\$##g")
            mkdir -p pkg/usr/share/locale/${LANG}/LC_MESSAGES
            ln -s ${i} pkg/usr/share/locale/${LANG}/LC_MESSAGES/incus.mo
          done

          cd pkg

          if [ "${PKGOS}" = "debian-13" ] || [ "${PKGOS}" = "ubuntu-24.04" ] || [ "${PKGOS}" = "ubuntu-26.04" ]; then
            sed -i debian/control \
              -e "s/LIBPNG16/libpng16-16t64/g" \
              -e "s/LIBUSBREDIRPARSER1/libusbredirparser1t64/g" \
              -e "s/LIBAIO1/libaio1t64/g" \
              -e "s/LIBBTRFS0/libbtrfs0t64/g" \
              -e "s/LIBUV1/libuv1t64/g"

            if [ "${PKGOS}" = "ubuntu-26.04" ]; then
              sed -i debian/control \
                -e "s/LIBGPGME11/libgpgme45/g"
            else
              sed -i debian/control \
                -e "s/LIBGPGME11/libgpgme11t64/g"
            fi
          else
            sed -i debian/control \
              -e "s/LIBPNG16/libpng16-16/g" \
              -e "s/LIBUSBREDIRPARSER1/libusbredirparser1/g" \
              -e "s/LIBAIO1/libaio1/g" \
              -e "s/LIBBTRFS0/libbtrfs0/g" \
              -e "s/LIBGPGME11/libgpgme11/g" \
              -e "s/LIBUV1/libuv1/g"
          fi

          if [ "${PKGOS}" = "debian-13" ] || [ "${PKGOS}" = "ubuntu-26.04" ]; then
            sed -i debian/control \
              -e "s/LIBFUSE3/libfuse3-4/g"
          else
            sed -i debian/control \
              -e "s/LIBFUSE3/libfuse3-3/g"
          fi

          if [ "${PKGOS}" = "ubuntu-26.04" ]; then
            sed -i debian/control \
              -e "s/LIBNET1/libnet9/g"
          else
            sed -i debian/control \
              -e "s/LIBNET1/libnet1/g"
          fi

          if [ "${PKGOS}" = "debian-13" ] || [ "${PKGOS}" = "ubuntu-26.04" ]; then
            sed -i debian/control \
              -e "s/^  LIBVIRGL,$/  libdrm-amdgpu1,\n  libdrm2,\n  libegl1,\n  libepoxy0,\n  libgbm1,/"
            echo "opt/incus/lib/libvirglrenderer.so*" >> debian/incus.install
          else
            sed -i debian/control \
              -e "/^  LIBVIRGL,$/d"
          fi

          dch --package incus --create -D ${CODENAME} -M -m "Automated Incus stable build" -v 1:$(echo ${INCUS_TAG} | sed -e "s/v//" -e "s/.0$//")-$(echo ${PKGOS} | sed "s/-//g")-$(date -u +%Y%m%d%H%M) --force-distribution
          dpkg-buildpackage -b

          cd ..
          mkdir out
          mv incus_* out/
          mv incus-base_* out/
          mv incus-client_* out/
          mv incus-extra_* out/
          mv incus-ui-canonical_* out/

      - name: Upload resulting build
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: out/*
