name: Builds
on:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-incus:
    name: Build Incus
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
          - debian-11
          - debian-12
          - debian-13
        arch:
          - amd64
          - arm64
        exclude:
          - os: debian-11
            arch: arm64
    runs-on:
      - self-hosted
      - cpu-4
      - mem-8G
      - disk-50G
      - arch-${{ matrix.arch }}
      - image-${{ matrix.os }}

    env:
      OS_ARCH: ${{ matrix.arch }}
      OS_NAME: ${{ matrix.os }}
      HOME: "/root/"
      PKG_CONFIG_PATH: "/opt/incus/lib/pkgconfig/"
      CGO_LDFLAGS: "-L/opt/incus/lib/"
      CGO_CFLAGS: "-I/opt/incus/include/"
      LD_LIBRARY_PATH: "/opt/incus/lib/"
      CPATH: "/opt/incus/include/"
      PATH: "/opt/incus/bin:/root/.cargo/bin:/usr/local/go/bin:/usr/local/node/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

      # Linux Containers projects
      DISTROBUILDER_TAG: "distrobuilder-3.2"
      INCUS_TAG: "v6.12.0"
      INCUS_UI_CANONICAL_TAG: "incus-0.15.3"
      LXCFS_TAG: "v6.0.4"
      LXC_TAG: "v6.0.4"

      # External dependencies
      COWSQL_TAG: "v1.15.8"
      CRIU_TAG: "v4.1"
      EDK2_TAG: "edk2-stable202411"
      GOLANG_TAG: "go1.24.3"
      LEGO_TAG: "v4.23.1"
      LIBTPMS_TAG: "v0.10.0"
      LIBURING_TAG: "liburing-2.9"
      MINIO_MC_TAG: "RELEASE.2025-04-16T18-13-26Z"
      MINIO_TAG: "RELEASE.2025-04-22T22-12-26Z"
      NASM_TAG: "nasm-2.16.03"
      NVIDIA_CONTAINER_TAG: "v1.17.6"
      QEMU_TAG: "v9.0.4"
      RAFT_TAG: "v0.22.1"
      SEABIOS_TAG: "rel-1.16.3"
      SKOPEO_TAG: "v1.18.0"
      SWTPM_TAG: "v0.10.1"
      UMOCI_TAG: "v0.5.0"
      VIRTIOFSD_TAG: "v1.13.1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config --global --add advice.detachedHead false
          git config --global user.email "noreply@zabbly.com"
          git config --global user.name "Zabbly Incus build"

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install --no-install-recommends --yes \
            acpica-tools \
            asciidoc \
            autoconf \
            automake \
            bison \
            bmake \
            build-essential \
            curl \
            debhelper \
            devscripts \
            dosfstools \
            expect \
            flex \
            gawk \
            gettext \
            git \
            iproute2 \
            libacl1-dev \
            libaio-dev \
            libapparmor-dev \
            libbtrfs-dev \
            libcap-dev \
            libcap-ng-dev \
            libdbus-1-dev \
            libdevmapper-dev \
            libelf-dev \
            libfuse3-dev \
            libglib2.0-dev \
            libgnutls28-dev \
            libgpgme-dev \
            libjson-glib-dev \
            libnet1-dev \
            libnl-3-dev \
            libnuma-dev \
            libpam0g-dev \
            libpixman-1-dev \
            libpng-dev \
            libprotobuf-c-dev \
            libprotobuf-dev \
            librbd-dev \
            libseccomp-dev \
            libselinux1-dev \
            libspice-server-dev \
            libsqlite3-dev \
            libssl-dev \
            libsystemd-dev \
            libtirpc-dev \
            libtool \
            libudev-dev \
            libusb-1.0-0-dev \
            libusbredirhost-dev \
            libuv1-dev \
            lsb-release \
            mtools \
            ninja-build \
            pkg-config \
            protobuf-c-compiler \
            protobuf-compiler \
            python3-cryptography \
            python3-jinja2 \
            python3-pexpect \
            python3-pip \
            python3-setuptools \
            python3-venv \
            rsync \
            socat \
            uuid-dev \
            xmlto \
            xorriso

          apt-get install --no-install-recommends --yes systemd-dev || true

          pip3 install meson || pip3 install meson --break-system-packages
          pip3 install tomli || pip3 install tomli --break-system-packages

      - name: Install backported debhelper (on focal)
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          if [ "${OS_ARCH}" = "amd64" ]; then
              echo "deb http://archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse" >> /etc/apt/sources.list
          else
              echo "deb http://ports.ubuntu.com/ubuntu-ports focal-backports main restricted universe multiverse" >> /etc/apt/sources.list
          fi
          apt-get install -t focal-backports debhelper --yes

      - name: Install backported git (on focal)
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          apt-get install software-properties-common --yes
          add-apt-repository ppa:git-core/ppa --yes
          apt-get install git --yes

      - name: Install Go
        run: |
          curl -sL "https://go.dev/dl/${GOLANG_TAG}.linux-${OS_ARCH}.tar.gz" | tar -C /usr/local/ -zx
          go version

      - name: Install Rust
        run: |
          curl -sL https://sh.rustup.rs -o install-rust.sh
          bash install-rust.sh -y

      - name: Install Node
        run: |
          [ "${OS_ARCH}" = "amd64" ] && NODE_ARCH=x64
          [ "${OS_ARCH}" = "arm64" ] && NODE_ARCH=arm64


          mkdir /usr/local/node/
          curl -sL "https://nodejs.org/dist/v22.11.0/node-v22.11.0-linux-${NODE_ARCH}.tar.xz" | tar -C /usr/local/node/ -Jx --strip-components=1

      - name: Build environment
        run: |
          mkdir /build/
          mkdir -p \
            /opt/incus/bin/ \
            /opt/incus/include/ \
            /opt/incus/lib/ \
            /opt/incus/lib/systemd/system/ \
            /opt/incus/share/

      - name: Get the code
        run: |
          # Ubuntu 20.04 is no longer supported by recent QEMU.
          [ "${OS_NAME}" = "ubuntu-20.04" ] && QEMU_TAG="v9.0.2"

          git clone https://github.com/lxc/distrobuilder /build/distrobuilder --depth 1 -b "${DISTROBUILDER_TAG}"
          git clone https://github.com/lxc/lxc /build/lxc -b "${LXC_TAG}"
          git clone https://github.com/lxc/lxcfs /build/lxcfs --depth 1 -b "${LXCFS_TAG}"
          git clone https://github.com/lxc/incus /build/incus -b "${INCUS_TAG}"
          git clone https://github.com/zabbly/incus-ui-canonical /build/incus-ui-canonical --depth 1 -b "${INCUS_UI_CANONICAL_TAG}"

          git clone https://github.com/axboe/liburing /build/liburing --depth 1 -b "${LIBURING_TAG}"
          git clone https://github.com/checkpoint-restore/criu /build/criu --depth 1 -b "${CRIU_TAG}"
          git clone https://github.com/containers/skopeo /build/skopeo --depth 1 -b "${SKOPEO_TAG}"
          git clone https://github.com/cowsql/cowsql /build/cowsql --depth 1 -b "${COWSQL_TAG}"
          git clone https://github.com/cowsql/raft /build/raft --depth 1 -b "${RAFT_TAG}"
          git clone https://github.com/go-acme/lego /build/lego --depth 1 -b "${LEGO_TAG}"
          git clone https://github.com/minio/mc /build/mc --depth 1 -b "${MINIO_MC_TAG}"
          git clone https://github.com/minio/minio /build/minio --depth 1 -b "${MINIO_TAG}"
          git clone https://github.com/NVIDIA/libnvidia-container /build/libnvidia-container --depth 1 -b "${NVIDIA_CONTAINER_TAG}"
          git clone https://github.com/opencontainers/umoci /build/umoci --depth 1 -b "${UMOCI_TAG}"
          git clone https://github.com/stefanberger/libtpms /build/libtpms --depth 1 -b "${LIBTPMS_TAG}"
          git clone https://github.com/stefanberger/swtpm /build/swtpm --depth 1 -b "${SWTPM_TAG}"
          git clone https://github.com/tianocore/edk2 /build/edk2 --recurse-submodules --shallow-submodules --depth 1 -b "${EDK2_TAG}"
          git clone https://gitlab.com/qemu-project/qemu /build/qemu --depth 1 -b "${QEMU_TAG}"
          git clone https://gitlab.com/qemu-project/seabios /build/seabios --depth 1 -b "${SEABIOS_TAG}"
          git clone https://gitlab.com/virtio-fs/virtiofsd /build/virtiofsd --depth 1 -b "${VIRTIOFSD_TAG}"

          mkdir /build/nasm/
          curl -sL "https://www.nasm.us/pub/nasm/releasebuilds/$(echo ${NASM_TAG} | cut -d- -f2)/${NASM_TAG}.tar.gz" --resolve www.nasm.us:443:198.137.202.136 | tar -C /build/nasm/ -zx --strip-components=1

      - name: Build liburing
        run: |
          cd /build/liburing
          ./configure --prefix=/opt/incus
          make

          mkdir -p /build/target/liburing/
          DESTDIR=/build/target/liburing make install
          rsync -a /build/target/liburing/opt/incus/include/* /opt/incus/include/
          rsync -a /build/target/liburing/opt/incus/lib/* /opt/incus/lib/

      - name: Build raft
        run: |
          cd /build/raft
          autoreconf -i
          ./configure --prefix=/opt/incus
          make

          mkdir -p /build/target/raft/
          DESTDIR=/build/target/raft/ make install
          rsync -a /build/target/raft/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/raft/opt/incus/lib/ /opt/incus/lib/

      - name: Build cowsql
        run: |
          cd /build/cowsql
          autoreconf -i
          ./configure --prefix=/opt/incus
          make

          mkdir -p /build/target/cowsql/
          DESTDIR=/build/target/cowsql/ make install
          rsync -a /build/target/cowsql/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/cowsql/opt/incus/lib/ /opt/incus/lib/

      - name: Build LXC
        run: |
          cd /build/lxc

          git cherry-pick 2663712e8fa8f37e0bb873185e2d4526dc644764  # start: Re-introduce first SET_DUMPABLE call

          meson setup build \
                  --prefix=/opt/incus \
                  --libdir=/opt/incus/lib \
                  -Dexamples=false \
                  -Dman=false \
                  -Dtools=false \
                  -Dtests=false \
                  -Dmemfd-rexec=false \
                  -Dapparmor=true \
                  -Dseccomp=true \
                  -Dselinux=true \
                  -Dcapabilities=true \
                  -Dio-uring-event-loop=false
          meson compile -C build

          mkdir -p /build/target/lxc/
          DESTDIR=/build/target/lxc/ meson install -C build
          rsync -a /build/target/lxc/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/lxc/opt/incus/lib/ /opt/incus/lib/
          mkdir -p /opt/incus/share/lxc/config/common.conf.d/
          mkdir -p /opt/incus/share/lxc/hooks/
          cp /build/target/lxc/opt/incus/share/lxc/hooks/nvidia /opt/incus/share/lxc/hooks/

      - name: Build LXCFS
        run: |
          REPO="${PWD}"

          cd /build/lxcfs
          meson setup build \
                  --prefix=/opt/incus \
                  --libdir=/opt/incus/lib \
                  -Ddocs=false \
                  -Dtests=false
          meson compile -C build

          mkdir -p /build/target/lxcfs/
          DESTDIR=/build/target/lxcfs/ meson install -C build
          rsync -a /build/target/lxcfs/opt/incus/bin/ /opt/incus/bin/
          rsync -a /build/target/lxcfs/opt/incus/share/ /opt/incus/share/
          rsync -a /build/target/lxcfs/opt/incus/lib/ /opt/incus/lib/

          sed -i "s#/var/lib/lxcfs#/var/lib/incus-lxcfs#g" /opt/incus/share/lxcfs/lxc.mount.hook
          patch -p1 /opt/incus/share/lxcfs/lxc.mount.hook < "${REPO}/patches/lxcfs-0001-hook.patch"

      - name: Build Incus
        run: |
          REPO="${PWD}"

          cd /build/incus

          git cherry-pick 0cc2e3362b2792d8a1fc0fe3c250ef0b03a10ba5  # doc: Fix default value of ipv4.dhcp.gateway to IPv4 address
          git cherry-pick e7a7cf2c2f793f3644e9e000a00a93e9a98c5e16  # doc: Fix default value of ipv6.routes network_bridge
          git cherry-pick 0a99902a372b69d5012f8990104e55bcd293a960  # doc: Fix Debian 12 nickname
          git cherry-pick 154fd110910d74a09c75cfa2bc548662827fde55  # incusd/firewall: Clear correct table for address sets
          git cherry-pick 14e8e33305c434743e642fdb6f9db18f7a49a4b4  # incusd/firewall: Remove unused part of nftables structs
          git cherry-pick 79651bb3bdf4c50d238e38c78e1cf82309084a16  # incusd/dns: fix typo in error log
          git cherry-pick 5e5f683ba080e1b191b1189def24d29cd8b225b4  # incusd: Rename reverters from revert to reverter
          git cherry-pick ba9acae39b95f11f4986769d38c96798b228ead2  # incus-user: Rename reverters from revert to reverter
          git cherry-pick 9100f23fca23f10f1c859687ab526888868f1452  # incus-agent: Rename reverters from revert to reverter
          git cherry-pick 07640580c72923d13eb59413f9746a4a3e2906d8  # internal/linux: Rename reverters from revert to reverter
          git cherry-pick 37a74bc63bd46887030a0810f6fd18e551ec9a64  # incusd: Rename reverters from revert to reverter
          git cherry-pick 79ee9be3a137e6449e75fdfc45ec6f1ee37e252c  # incusd: Use errors.Is instead of direct error comparison Replace direct error comparison with errors.Is checks to avoid potential bugs with wrapped errors.
          git cherry-pick 683085aeee10cef61679be12a74a59576429efe5  # incusd: Use errors.As instead of type switching Replace type switching on an error with errors.As to avoid potential bugs.
          git cherry-pick 80d4806a9cc898e1556a5303e6ff6dbc55d214f6  # incus-user: Use errors.Is instead of direct error comparison
          git cherry-pick 4b6254088d14bfc82c5d6b2307f4e2dbf5d4d708  # incus: Use errors.Is instead of direct error comparison
          git cherry-pick 1f6c20c7ecb6492c533c564e6b9e8adb7ecc0f1d  # internal/server: Use errors.Is instead of direct error comparison
          git cherry-pick ae49dd1e885ccb4cc8f8e6f6da34bf65ddc016f4  # internal/linux: Use errors.Is instead of direct error comparison
          git cherry-pick 314a7ef87157c47e5a854b5fba91e23bf1f1c001  # internal/eagain: Use errors.Is instead of direct error comparison
          git cherry-pick 86c8b61142c2187aaa31401a2e13adabfaa2b190  # internal/server: replace manual unwrap call with errors.As
          git cherry-pick 92d5bfe0652cfbce1dd1ba78c0b1717c50fed8fd  # internal/rsync: replace manual unwrap call with errors.As
          git cherry-pick 8ff55fd7a29e4a6ea70f9ee5166abb331d7461f2  # internal/server: Use errors.As instead of type switching Replace type switching on an error with errors.As to avoid potential bugs.
          git cherry-pick 808f01960f38bee0bf1aabf5b1d2f38f067e9d5c  # internal/linux: Use errors.As instead of type switching Replace type switching on an error with errors.As to avoid potential bugs.
          git cherry-pick cafdc8d24a1d496732cc563f62c15ab6b8e584d3  # internal/server: make all methods on the zfs struct take a pointer
          git cherry-pick 4da5e501f951920b254912f5c9f457f5365b34d8  # internal/server: change method isAllowed on the dnsHandler struct into a static function
          git cherry-pick f3e9cdec7da122476836cf8e72cc5f0c5d3fe80a  # shared/api: unify methods declared on the Instance struct to all take a pointer
          git cherry-pick 3bfbd326ba5ada722b96461af9d756e6f92deabe  # generate-database: unify methods declared on the Field struct to all take a pointer
          git cherry-pick 0aa7b2056db24064f9c6a99358c8857a6c58b015  # internal/server: refactor getting heartbeat mode name into a function
          git cherry-pick e96697a7568a4a993464bbf09326ee6ffe28a84b  # internal/server: rename close to closeFunc
          git cherry-pick 52bf3aa932e6fde37adbd6b1a900e0448c1d5d4b  # internal/version: Rename variables to better represent what they are used for
          git cherry-pick 73c08ac6ff93485058340b520624b43e57fdacc2  # client: Rename variables because error is a builtin interface name
          git cherry-pick 9279f5f11a2a0c015295d874be80c7f20914e64d  # incusd: Rename variables because recover and min are builtin functions
          git cherry-pick e7e184168a20ecf6ab00ea6adfe72f74f3109550  # incusd: Rename variables because they collide with builtin function names
          git cherry-pick 9dfeefca13a147fe2bab7a036abccad8f3f52979  # generate-database/db: Un-export joinConfig
          git cherry-pick 94d317af385409bf628d9b860e61730aaca02743  # incusd: Introduce patchRun type
          git cherry-pick 661f772446f9b44045ebb6c09052a665f769deb0  # incusd: Remove unused parameter names in cobra commands
          git cherry-pick 14eca14a346953b23e26889a32195bf72e70cd56  # incusd: Remove unused parameters or rename unused parameters to _
          git cherry-pick 11c4ff89e0883c06959f4d377bf7915d388969dc  # incusd: Un-export command functions
          git cherry-pick 1ff7f6cb7b2e9f80b534fc911f006bc08d32e189  # incusd: Don't export internal websocket struct functions
          git cherry-pick 983550b494abc03ec49d47e716518b0eb7574571  # incusd: Don't export internal migration struct functions
          git cherry-pick cd1b9f2ad061e0fe12c22a64ff040f29e35168b4  # incusd: Fix import shadowing
          git cherry-pick a0cbf878b0ea083682c7dae1d66bc1b826f83218  # incusd/instance/drivers: Rewrite config entries as maps
          git cherry-pick b268f4d7f2597be601fb102bd1ce6bc997e622ef  # incusd/scriptlet/qemu: Remove legacy wrapper
          git cherry-pick 5d6defba1c216ecf8c991ce7830c1b15bcd42710  # incusd/instance/drivers: Fix tests
          git cherry-pick c321125cc1dafa159a598f0423b3c448f5273c04  # incusd/instance/drivers: Use fmt.Fprintf
          git cherry-pick e9e8ed6ddab8ad9e16ecfce4a79ba21525f50ba2  # incusd/firewall/nftables: Fix handling of address set deletion
          git cherry-pick c4c2ce0588cc1d82b6ec4ef272f4eb12ed64168e  # incusd/instance/qemu: Handle agents with limited information
          git cherry-pick d56f573f043df0f1aa0e159687accc82e3cff83e  # incusd: remove conditional check that is always true
          git cherry-pick 7f6bfcd3c0d45c4c0d064648b0374fa1115ec1b3  # incusd: remove outdated comment about no longer existing force option
          git cherry-pick 9cf935f21844d14997d54ceb22bdb30795e9f66a  # incusd: remove code that was unreachable in api_internal.go
          git cherry-pick 01b5d23ac39693cb35971ef5ab8491e25468a45d  # incusd: remove code that was unreachable in api_internal.go
          git cherry-pick 4ce93a1873b37fa8a8d49c5d6d7b94caf8c79b82  # shared/archive: remove unnecessary err check
          git cherry-pick 50f39024d02be7b5935ca859cf97fb4220da3a8f  # incusd: refactor condition checks that are always true or false respectively
          git cherry-pick f66330b65014e33fed7a0f89f52d11c94dfa4d6c  # cmd/incus: refactor unnecessary err condition checks
          git cherry-pick 772314c1a2c01e0eb186ba32526fa8ce8f307576  # internal/linux: refactor unnecessary err condition check
          git cherry-pick 0f47aaf7bdaba8e9258e9a70bb098d7fbbb0052d  # client: remove unnecessary err check and unused variable ioErr
          git cherry-pick 67c57ce193ff0dfd6326c46ca44cda27f9eb74ac  # incusd: refactor process kill error being ignored
          git cherry-pick 6215fcce480a4b6270cd92ac82aacd1798152161  # incusd/instance: fix device finding logic
          git cherry-pick 4c46eca995f96d3214440bb0c44cca3b1bf64cd4  # incusd/instance/drivers: Make test ignore host-nodes order
          git cherry-pick ec9377e61b77324e1413ba16d1ac697705ac27a6  # incus: refactor admin_init.go config initialization
          git cherry-pick 2f5417b29489d3e2d09a5551653c53a660ff3c1e  # incusd/network/ovn: Wait up to 10s for OVN northd to allocate an IP
          git cherry-pick e5d2ba5e19aa4040443c74f7c5147422bc06ff95  # incusd/dnsmasq: refactor DHCPValidIP condition checks
          git cherry-pick 15272e6a4ceb83a32605f26a520a846a6d348c6a  # incusd: Prevent panic when VolumeSize is missing
          git cherry-pick 9d04644dfe18a4652eacce27ef75fae4beded99d  # incusd/migrate: Set write time limit for sendControl method
          git cherry-pick a467603c4f8780f9ee807218d20595cdbeb56b2b  # incusd/network/bridge: Add missing line breaks
          git cherry-pick 4f30ef3b71abd5159e4d0b92ef2d0e329fdc8eaa  # Remove gopkg.in/tomb.v2 dependency
          git cherry-pick 773e8916da7baf563df43f81c59ed9f37f59bf32  # incusd/instance/qemu: Don't allow hotplug when at maxmem
          git cherry-pick a58aa19a67ad84cc182596387a3adeceec3f401c  # incusd: rename variable `mux` to `router` so it does not collide with the package of the same name
          git cherry-pick 63386dd0650b7342ac7d11b8273c5d3b330b9557  # cmd/incus-agent: rename variable `mux` to `router` so it does not collide with the package of the same name
          git cherry-pick 4c8ff50cbbc3b500db79b0027c2a57b4fa0a4e7c  # incusd: rename all instances of sha256.New() to hash256 so they dont collide with the package name
          git cherry-pick 9d8dee1a3529ea467316f354fdfaf6d0f6c3c2ad  # client: rename all instances of sha256.New() to hash256 so they dont collide with the package name
          git cherry-pick 7427eeb87777ca6719af9db14af7a37bba6e0238  # cmd/incus-migrate: add missing switch case with explicit comment
          git cherry-pick f1e237787c36e1ab7ab45b124de924cf1c8fb2f0  # incusd: internalize the default case into the switch so it covers all iota constants
          git cherry-pick f557d9f8f3cb6fe60cbfa2a6ef756b3ede4700d6  # internal/filter: internalize the default case into the switch so it covers all iota constants
          git cherry-pick eea5c768afc89f4d091e1f52d483f72baa91d594  # incusd: add missing err handling for transactions
          git cherry-pick fe7d640bc317d72465e42e3cfb58f8022d798714  # incusd/storage: Fix migration error due to rounding
          git cherry-pick b54d6cdef1d16eb5a68fb9f98c84aed200183b11  # incusd/storage/zfs: Optimize snapshot deletion
          git cherry-pick 9e47475564f07b121e4da1b74c07670f121b7ccf  # incusd: add more ErrorList tests for error formatting
          git cherry-pick 0630ab52ed546fed1f79a479c286bb1e7b7efb2b  # incusd: refactor Error implementation of ErrorList
          git cherry-pick af836804a96db0ccda2e4d8bbf9d2821d591e588  # incusd: make all functions on ErrorList take a pointer receiver
          git cherry-pick 36932ea0895d40d8f009926d15852f8228cde3f7  # incusd: rename Error struct and make it private
          git cherry-pick 8178df5c69237548e3188436a1d93b062b04d591  # internal/iprange: add tests for the iprange.Range struct
          git cherry-pick caf04492ea1cfce3db7bde3c804a766cb20980ff  # internal/dnsutil: remove unused package dnsutil
          git cherry-pick 5a6dc154278fb4d582b8a184dbb6c33fe0c90c6d  # incusd: rename instanceActionToOptype to instanceActionToOpType
          git cherry-pick 348dc783998b87d11fc0ead119ae697e7a877a09  # incusd/instance/drivers: Rewrite QEMU config override logic
          git cherry-pick 0e6cfd4c7da01e67fd7ddaa2074ae97b38d28b3f  # incusd/instance/drivers: Adapt the tests to the new override logic
          git cherry-pick 883d9ac5eb9b050b2c4c09dadab172eca95826b2  # incusd/instance/drivers: Drop old RegEx parser and return proper errors
          git cherry-pick 997a9bd3708667d4ba53399c49dc0942a6559cdb  # incusd/instance/drivers: Update tests
          git cherry-pick 8be53f0782c463b2f15a60be1e98a69e24cb4231  # incusd: remove redundant size 0 initialization for maps
          git cherry-pick 6af654169528a2c0d20b9277b9e57e8ca353a21a  # cmd/generate-config: remove redundant size 0 initialization for maps
          git cherry-pick da3188a885e450159e584f8ddb1d5b02b7596e27  # cmd/lxc-to-incus: remove redundant size 0 initialization for maps
          git cherry-pick edeff45dd960a2f1b40f5318644753b1f23291f5  # incusd/certificates: Properly handle PEM encoding on POST
          git cherry-pick d4fec1b3e9c833a44cceeef7bcbc01f788d5bb36  # incusd/instance/qemu: Don't allow QEMU RSS to exceed memory limit
          git cherry-pick e144839781135c904696c588dde57f5eb54e841a  # incusd/dns: Restart DNS server on failure
          git cherry-pick 9bc50ad8571bef052b7ce21889093014656c6b8f  # incusd/instance/qemu: Limit memory hotplug slots to 8
          git cherry-pick d7b4df82be36395cad10061082f1b46afc8d55a1  # incusd/device/sriov: Handle cards without configurable spoof checking
          git cherry-pick f6cbdf991d18bb5823bc7178febae7936149d989  # incusd/firewall/nftables: disable UDP checksum validation for packets on bridged network
          git cherry-pick cd73a90f7459e5c3a57505835b4f4c34e6b5722c  # client: Add certificate handling to ApplyServerPreseed
          git cherry-pick 7eaacafc19465698fdedb3890ddf8293cc9aecb4  # shared/api: Add Certificates to InitLocalPreseed
          git cherry-pick 5a9fccade08de99ab41415a1f28e249ad7e8458e  # incusd: Move cluster resource caching logic
          git cherry-pick 1c3cbba48ec985f30e1b9f840566f749e36779ab  # incusd/main_forknet: Implement stateful DHCPv6
          git cherry-pick c6183327ce96ea269cabc85541bcacaccaf97b3e  # incusd/main_forknet: Add delay to wait for IPv6 link-local
          git cherry-pick ddb6e16610f816dcd254480257730e90fc25bfa9  # incusd/main_forknet: Add stateless DHCPv6 support
          git cherry-pick b237a7a0f0ec493564c77a83df3e161794eec492  # internal/util: Add Incus OS detection
          git cherry-pick 6860d9196002219c187fab1793f438654428fc8a  # incusd: Use IsIncusOS
          git cherry-pick 29a3b2f697e2b4bad7f1cbd47330347768afb057  # incusd/metrics: Include OS metrics on Incus OS
          git cherry-pick 939cdb9f7769c44edc78d9925b9a6e6a03a01472  # incusd/storage/ceph: Fix parent tracking for VMs
          git cherry-pick 59f2c354747b07e84b4df6fc084aef4a7178f6ec  # incusd/main_forknet: Don't touch resolv.conf when no leases
          git cherry-pick 8520c07c8e5e241ae1faa16162ba14dd24313e7c  # incusd/storage/ceph: Fix typo in parseParent
          git cherry-pick 54245abe155d07026929287619e4e92f67053a59  # incusd/instances: Tweak storage migration errors
          git cherry-pick d9bdf39fe200c733bc29a0c95129ede9908028e6  # incusd/instances_post: Prevent pointless device overrides
          git cherry-pick 769d23b9650da74b3018163e2fc85c20e659d13a  # incusd/instance: Fix incorrect cluster.Connect call

          go build -o "/opt/incus/bin/fuidshift" github.com/lxc/incus/v6/cmd/fuidshift
          go build -o "/opt/incus/bin/incus" github.com/lxc/incus/v6/cmd/incus
          go build -o "/opt/incus/bin/incus-benchmark" github.com/lxc/incus/v6/cmd/incus-benchmark
          go build -o "/opt/incus/bin/incus-migrate" github.com/lxc/incus/v6/cmd/incus-migrate
          go build -o "/opt/incus/bin/incus-simplestreams" github.com/lxc/incus/v6/cmd/incus-simplestreams
          go build -o "/opt/incus/bin/incus-user" github.com/lxc/incus/v6/cmd/incus-user
          go build -o "/opt/incus/bin/incusd" -tags=libsqlite3 github.com/lxc/incus/v6/cmd/incusd
          go build -o "/opt/incus/bin/lxc-to-incus" github.com/lxc/incus/v6/cmd/lxc-to-incus
          go build -o "/opt/incus/bin/lxd-to-incus" -tags=libsqlite3 github.com/lxc/incus/v6/cmd/lxd-to-incus

          mkdir -p /opt/incus/agent
          if [ "$(uname -m)" = "x86_64" ]; then
              GOARCH=amd64 CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.linux.x86_64" -tags=agent,netgo github.com/lxc/incus/v6/cmd/incus-agent
              GOARCH=386 CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.linux.i686" -tags=agent,netgo github.com/lxc/incus/v6/cmd/incus-agent
          elif [ "$(uname -m)" = "aarch64" ]; then
              GOARCH=arm64 CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.linux.aarch64" -tags=agent,netgo github.com/lxc/incus/v6/cmd/incus-agent
          fi

          make build-mo
          mkdir -p /opt/incus/share/locale
          cp po/*.mo /opt/incus/share/locale/

          make doc
          cp -R doc/html /opt/incus/doc

          mkdir -p /opt/incus/share/completions/
          /opt/incus/bin/incus completion bash > /opt/incus/share/completions/bash
          /opt/incus/bin/incus completion fish > /opt/incus/share/completions/fish
          /opt/incus/bin/incus completion zsh > /opt/incus/share/completions/zsh

      - name: Build UI (canonical)
        run: |
          REPO="${PWD}"

          cd /build/incus-ui-canonical

          # Complete re-branding.
          find -type f -name "*.ts" -o -name "*.tsx" -o -name "*.scss" | xargs sed -i -f "${REPO}/patches/ui-canonical-renames.sed"

          npm install yarn --global
          yarn install
          yarn build

          mkdir -p /opt/incus/ui-canonical/
          rsync -a /build/incus-ui-canonical/build/ui/ /opt/incus/ui-canonical/

      - name: Build Distrobuilder
        run: |
          cd /build/distrobuilder
          go build -o "/opt/incus/bin/distrobuilder" github.com/lxc/distrobuilder/distrobuilder

      - name: Build CRIU
        if: ${{ matrix.os != 'ubuntu-20.04' }}
        run: |
          cd /build/criu
          make WERROR=0
          cp criu/criu /opt/incus/bin/

      - name: Build libnvidia-container
        run: |
          REPO="${PWD}"

          cd /build/libnvidia-container
          patch -p1 < "${REPO}/patches/nvidia-0001-Fix-for-22.04-build.patch"
          patch -p1 < "${REPO}/patches/nvidia-0002-pre-load-libdl.patch"
          make prefix=/

          mkdir /build/target/libnvidia-container
          DESTDIR=/build/target/libnvidia-container make install prefix=/
          rsync -a /build/target/libnvidia-container/bin/ /opt/incus/bin/
          rsync -a /build/target/libnvidia-container/include/ /opt/incus/include/
          rsync -a /build/target/libnvidia-container/lib/ /opt/incus/lib/

      - name: Build minio
        run: |
          cd /build/minio
          make build
          cp minio /opt/incus/bin/

      - name: Build minio client
        run: |
          cd /build/mc
          make build
          cp mc /opt/incus/bin/

      - name: Build seabios
        if: ${{ matrix.arch == 'amd64' }}
        run: |
          REPO="${PWD}"

          cd /build/seabios

          # Build a traditional seabios.
          make clean distclean
          echo "CONFIG_QEMU=y" > .config
          echo "CONFIG_QEMU_HARDWARE=y" >> .config
          echo "CONFIG_BOOTSPLASH=n" >> .config
          echo "CONFIG_ROM_SIZE=256" >> .config
          echo "CONFIG_XEN=n" >> .config
          echo "CONFIG_PVSCSI=n" >> .config
          echo "CONFIG_ESP_SCSI=n" >> .config
          echo "CONFIG_LSI_SCSI=n" >> .config
          echo "CONFIG_MEGASAS=n" >> .config
          echo "CONFIG_MPT_SCSI=n" >> .config
          echo "CONFIG_FLOPPY=n" >> .config
          echo "CONFIG_FLASH_FLOPPY=n" >> .config
          make oldnoconfig V=1
          make V=1 PYTHON=python3

          mkdir -p /opt/incus/share/qemu/
          cp out/bios.bin /opt/incus/share/qemu/seabios.bin

      - name: Build nasm
        run: |
          REPO="${PWD}"

          cd /build/nasm
          patch -p1 < "${REPO}/patches/nasm-0000-disable-manpages.patch"
          ./configure --prefix=/opt/incus
          make

          mkdir -p /build/target/nasm/
          DESTDIR=/build/target/nasm make install
          rsync -a /build/target/nasm/opt/incus/bin/ /opt/incus/bin/

      - name: Build EDK2
        run: |
          REPO="${PWD}"

          cd /build/edk2
          patch -p1 < "${REPO}/patches/edk2-0001-force-DUID-LLT.patch"
          cp "${REPO}/patches/edk2-0002-logo.bmp" MdeModulePkg/Logo/Logo.bmp
          patch -p1 < "${REPO}/patches/edk2-0003-boot-delay.patch"
          patch -p1 < "${REPO}/patches/edk2-0004-gcc-errors.patch"
          patch -p1 < "${REPO}/patches/edk2-0005-Revert-ArmVirtPkg-make-EFI_LOADER_DATA-non-executabl.patch"
          patch -p1 < "${REPO}/patches/edk2-0006-disable-EFI-memory-attributes-protocol.patch"
          patch -p1 < "${REPO}/patches/edk2-0007-disable-UEFI-shell-under-SecureBoot.patch"

          EDK2_ARCH="X64"
          EDK2_PKG="OvmfPkg/OvmfPkgX64.dsc"
          EDK2_FV_CODE="OVMF_CODE"
          EDK2_FV_VARS="OVMF_VARS"
          if [ "$(uname -m)" = "aarch64" ]; then
              EDK2_ARCH="AARCH64"
              EDK2_PKG="ArmVirtPkg/ArmVirtQemu.dsc"
              EDK2_FV_CODE="QEMU_EFI"
              EDK2_FV_VARS="QEMU_VARS"
          fi

          build_edk2() {
              TARGET_CODE="$1"
              shift
              TARGET_VARS="$1"
              shift

              set -ex
              (
              cat << EOF
                  . ./edksetup.sh
                  make -C BaseTools ARCH=${EDK2_ARCH}
                  build -a ${EDK2_ARCH} -t GCC5 -b RELEASE -p ${EDK2_PKG} \
                    -DSMM_REQUIRE=TRUE \
                    -DSECURE_BOOT_ENABLE=TRUE \
                    -DNETWORK_IP4_ENABLE=TRUE \
                    -DNETWORK_IP6_ENABLE=TRUE \
                    -DNETWORK_TLS_ENABLE=TRUE \
                    -DNETWORK_HTTP_BOOT_ENABLE=TRUE \
                    -DTPM2_ENABLE=TRUE \
                    -DTPM2_CONFIG_ENABLE=TRUE \
                    $@
          EOF
              ) | bash -e

              cp Build/*/*/FV/${EDK2_FV_CODE}.fd "${TARGET_CODE}"
              cp Build/*/*/FV/${EDK2_FV_VARS}.fd "${TARGET_VARS}"

              if [ "$(uname -m)" = "aarch64" ]; then
                  truncate -s 64m "${TARGET_CODE}"
                  truncate -s 64m "${TARGET_VARS}"
              fi
          }

          mkdir -p "/opt/incus/share/qemu/"
          build_edk2 \
            "/opt/incus/share/qemu/OVMF_CODE.4MB.fd" \
            "/opt/incus/share/qemu/OVMF_VARS.4MB.fd" \
            -DFD_SIZE_4MB

          ln -s OVMF_CODE.4MB.fd /opt/incus/share/qemu/OVMF_CODE.fd
          ln -s OVMF_VARS.4MB.fd /opt/incus/share/qemu/OVMF_VARS.fd

      - name: Build libtmps
        run: |
          cd /build/libtpms
          ./autogen.sh
          ./configure --prefix=/opt/incus --with-tpm2 --with-openssl
          make

          mkdir -p /build/target/libtpms/
          DESTDIR=/build/target/libtpms make install
          rsync -a /build/target/libtpms/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/libtpms/opt/incus/lib/ /opt/incus/lib/

      - name: Build swtpm
        run: |
          cd /build/swtpm
          ./autogen.sh
          ./configure --prefix=/opt/incus --with-seccomp --with-openssl --without-cuse
          make

          mkdir -p /build/target/swtpm/
          DESTDIR=/build/target/swtpm make install
          rsync -a /build/target/swtpm/opt/incus/bin/ /opt/incus/bin/
          rsync -a /build/target/swtpm/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/swtpm/opt/incus/lib/ /opt/incus/lib/

      - name: Build virtiofsd
        run: |
          cd /build/virtiofsd
          cargo build --release
          cp target/release/virtiofsd /opt/incus/bin/

      - name: Build lego
        run: |
          cd /build/lego
          go build -o "/opt/incus/bin/lego" github.com/go-acme/lego/v4/cmd/lego

      - name: Build umoci
        run: |
          cd /build/umoci
          go build -o "/opt/incus/bin/umoci" github.com/opencontainers/umoci/cmd/umoci

      - name: Build skopeo
        run: |
          cd /build/skopeo
          go build -o "/opt/incus/bin/skopeo" github.com/containers/skopeo/cmd/skopeo

      - name: Build QEMU
        run: |
          REPO="${PWD}"

          cd /build/qemu
          patch -p1 < "${REPO}/patches/qemu-0001-usb-net-mac.patch"

          sed -i "s/^unset target_list$/target_list=\"$(uname -m)-softmmu\"/" configure
          ./configure \
                  --prefix=/opt/incus \
                  --libexecdir=bin \
                  --libdir=lib \
                  --disable-bochs \
                  --disable-cloop \
                  --disable-dmg \
                  --disable-docs  \
                  --disable-fuse  \
                  --disable-guest-agent \
                  --disable-parallels \
                  --disable-qed \
                  --disable-slirp \
                  --disable-user \
                  --disable-vdi \
                  --disable-vnc \
                  --disable-xen \
                  --disable-install-blobs \
                  --enable-attr \
                  --enable-cap-ng \
                  --enable-kvm \
                  --enable-libusb \
                  --enable-usb-redir \
                  --enable-linux-aio \
                  --enable-linux-io-uring \
                  --enable-numa \
                  --enable-pie \
                  --enable-png \
                  --enable-rbd \
                  --enable-seccomp \
                  --enable-spice \
                  --enable-system \
                  --enable-tcg \
                  --enable-tools \
                  --enable-vhost-crypto \
                  --enable-vhost-kernel \
                  --enable-vhost-net \
                  --enable-vhost-user \
                  --enable-virtfs
          make

          mkdir /build/target/qemu/
          DESTDIR=/build/target/qemu/ make install
          rsync -a /build/target/qemu/opt/incus/bin/ /opt/incus/bin/
          rsync -a /build/target/qemu/opt/incus/lib/ /opt/incus/lib/
          rsync -a /build/target/qemu/opt/incus/share/qemu/ /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/kvmvapic.bin /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/vgabios-qxl.bin /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/vgabios-virtio.bin /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/efi-virtio.rom /opt/incus/share/qemu/

      - name: Build Secure Boot firmware
        run: |
          REPO="${PWD}"

          cd /build/edk2

          FIRMWARE="OVMF"
          if [ "$(uname -m)" = "aarch64" ]; then
            FIRMWARE="AAVMF"
          fi

          cd "${REPO}/edk2-vars-generator"
          ./edk2-vars-generator -f "${FIRMWARE}" \
            -e /build/edk2/Build/*/*/*/EnrollDefaultKeys.efi \
            -s /build/edk2/Build/*/*/*/Shell.efi \
            -c "/opt/incus/share/qemu/OVMF_CODE.4MB.fd" \
            -V "/opt/incus/share/qemu/OVMF_VARS.4MB.fd" \
            -C "$(cat ${REPO}/zabbly-sb.oem.crt)" \
            -o "/opt/incus/share/qemu/OVMF_VARS.4MB.ms.fd"

      - name: Systemd units
        run: |
          cp systemd/*.service systemd/*.socket /opt/incus/lib/systemd/system/
          cp systemd/incusd /opt/incus/lib/systemd/
          cp systemd/incus-startup /opt/incus/lib/systemd/
          cp systemd/incus-user /opt/incus/lib/systemd/

      - name: Strip and cleanup binaries
        run: |
          rm -Rf /opt/incus/lib/debug/
          rm -Rf /opt/incus/include/
          rm -Rf /opt/incus/lib/pkgconfig/
          rm /opt/incus/lib/*.a /opt/incus/lib/*.la /opt/incus/lib/*/*.a /opt/incus/lib/*/*.la

          rm /opt/incus/bin/nasm
          rm /opt/incus/bin/ndisasm
          rm /opt/incus/bin/qemu-bridge-helper
          rm /opt/incus/bin/qemu-edid
          rm /opt/incus/bin/qemu-io
          rm /opt/incus/bin/qemu-nbd
          rm /opt/incus/bin/qemu-pr-helper
          rm /opt/incus/bin/qemu-storage-daemon
          rm /opt/incus/bin/swtpm_*
          rm /opt/incus/share/qemu/trace-events-all

          strip /opt/incus/agent/*
          strip /opt/incus/bin/*
          strip /opt/incus/lib/*so*

      - name: Make a Debian package
        env:
          PKGOS: ${{ matrix.os }}
        run: |
          [ "${PKGOS}" = "debian-11" ] && CODENAME=bullseye
          [ "${PKGOS}" = "debian-12" ] && CODENAME=bookworm
          [ "${PKGOS}" = "debian-13" ] && CODENAME=trixie
          [ "${PKGOS}" = "ubuntu-20.04" ] && CODENAME=focal
          [ "${PKGOS}" = "ubuntu-22.04" ] && CODENAME=jammy
          [ "${PKGOS}" = "ubuntu-24.04" ] && CODENAME=noble

          mkdir -p pkg/ pkg/lib/systemd/ pkg/opt/ pkg/usr/bin/ \
            pkg/usr/share/bash-completion/completions/ \
            pkg/usr/share/fish/vendor_completions.d/ \
            pkg/usr/share/zsh/vendor-completions/

          cp -R debian pkg/debian
          cp bin/* pkg/usr/bin/
          cp -R /opt/incus pkg/opt/
          cp -R etc pkg/etc
          mv pkg/opt/incus/lib/systemd/system pkg/lib/systemd/system

          ln -s /opt/incus/share/completions/bash pkg/usr/share/bash-completion/completions/incus
          ln -s /opt/incus/share/completions/fish pkg/usr/share/fish/vendor_completions.d/incus.fish
          ln -s /opt/incus/share/completions/zsh pkg/usr/share/zsh/vendor-completions/_incus

          ln -s /opt/incus/bin/lxd-to-incus pkg/usr/bin/lxd-to-incus

          ln -s /opt/incus/bin/fuidshift pkg/usr/bin/fuidshift
          ln -s /opt/incus/bin/incus-migrate pkg/usr/bin/incus-migrate
          ln -s /opt/incus/bin/incus-simplestreams pkg/usr/bin/incus-simplestreams

          mkdir -p pkg/var/lib/incus
          chmod 711 pkg/var/lib/incus

          mkdir -p pkg/var/log/incus
          chmod 700 pkg/var/log/incus

          mkdir -p pkg/usr/share/locale
          for i in /opt/incus/share/locale/*.mo; do
            LANG=$(echo $i | sed -e "s#.*/locale/##g" -e "s#.mo\$##g")
            mkdir -p pkg/usr/share/locale/${LANG}/LC_MESSAGES
            ln -s ${i} pkg/usr/share/locale/${LANG}/LC_MESSAGES/incus.mo
          done

          cd pkg

          if [ "${PKGOS}" = "debian-13" ] || [ "${PKGOS}" = "ubuntu-24.04" ]; then
            sed -i debian/control \
              -e "s/LIBPNG16/libpng16-16t64/g" \
              -e "s/LIBUSBREDIRPARSER1/libusbredirparser1t64/g" \
              -e "s/LIBAIO1/libaio1t64/g" \
              -e "s/LIBBTRFS0/libbtrfs0t64/g" \
              -e "s/LIBGPGME11/libgpgme11t64/g" \
              -e "s/LIBUV1/libuv1t64/g"
          else
            sed -i debian/control \
              -e "s/LIBPNG16/libpng16-16/g" \
              -e "s/LIBUSBREDIRPARSER1/libusbredirparser1/g" \
              -e "s/LIBAIO1/libaio1/g" \
              -e "s/LIBBTRFS0/libbtrfs0/g" \
              -e "s/LIBGPGME11/libgpgme11/g" \
              -e "s/LIBUV1/libuv1/g"
          fi

          if [ "${PKGOS}" = "debian-13" ]; then
            sed -i debian/control \
              -e "s/LIBFUSE3/libfuse3-4/g"
          else
            sed -i debian/control \
              -e "s/LIBFUSE3/libfuse3-3/g"
          fi

          dch --package incus --create -D ${CODENAME} -M -m "Automated Incus stable build" -v 1:$(echo ${INCUS_TAG} | sed -e "s/v//" -e "s/.0$//")-$(echo ${PKGOS} | sed "s/-//g")-$(date -u +%Y%m%d%H%M) --force-distribution
          dpkg-buildpackage -b

          cd ..
          mkdir out
          mv incus_* out/
          mv incus-base_* out/
          mv incus-client_* out/
          mv incus-extra_* out/
          mv incus-ui-canonical_* out/

      - name: Upload resulting build
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: out/*
