name: Builds
on:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-incus:
    name: Build Incus
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - debian-11
          - debian-12
          - debian-13
        arch:
          - amd64
          - arm64
        exclude:
          - os: debian-11
            arch: arm64
    runs-on:
      - self-hosted
      - cpu-4
      - mem-8G
      - disk-50G
      - arch-${{ matrix.arch }}
      - image-${{ matrix.os }}

    env:
      OS_ARCH: ${{ matrix.arch }}
      OS_NAME: ${{ matrix.os }}
      HOME: "/root/"
      PKG_CONFIG_PATH: "/opt/incus/lib/pkgconfig/"
      CGO_LDFLAGS: "-L/opt/incus/lib/"
      CGO_CFLAGS: "-I/opt/incus/include/"
      LD_LIBRARY_PATH: "/opt/incus/lib/"
      CPATH: "/opt/incus/include/"
      PATH: "/opt/incus/bin:/root/.cargo/bin:/usr/local/go/bin:/usr/local/node/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

      # Linux Containers projects
      DISTROBUILDER_TAG: "distrobuilder-3.2"
      INCUS_TAG: "v6.23.0"
      INCUS_UI_CANONICAL_TAG: "incus-0.19.9"
      LXCFS_TAG: "v6.0.6"
      LXC_TAG: "v6.0.6"

      # External dependencies
      COWSQL_TAG: "v1.15.9"
      CRIU_TAG: "v4.2"
      EDK2_TAG: "edk2-stable202602"
      GOLANG_TAG: "go1.26.2"
      LEGO_TAG: "v4.33.0"
      LIBTPMS_TAG: "v0.10.2"
      LIBURING_TAG: "liburing-2.14"
      MINIO_MC_TAG: "RELEASE.2025-08-13T08-35-41Z"
      MINIO_TAG: "RELEASE.2025-10-15T17-29-55Z"
      NASM_TAG: "nasm-2.16.03"
      NVIDIA_CONTAINER_TAG: "v1.19.0"
      QEMU_TAG: "v10.2.2"
      RAFT_TAG: "v0.22.1"
      SEABIOS_TAG: "rel-1.17.0"
      SKOPEO_TAG: "v1.22.2"
      SWTPM_TAG: "v0.10.1"
      TRUENAS_INCUS_CTL_TAG: "v0.7.7"
      VIRTIOFSD_TAG: "v1.13.3"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config --global --add advice.detachedHead false
          git config --global user.email "noreply@zabbly.com"
          git config --global user.name "Zabbly Incus build"

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install --no-install-recommends --yes \
            acpica-tools \
            asciidoc \
            autoconf \
            automake \
            bison \
            bmake \
            build-essential \
            curl \
            debhelper \
            devscripts \
            dosfstools \
            expect \
            flex \
            gawk \
            gettext \
            git \
            iproute2 \
            libacl1-dev \
            libaio-dev \
            libapparmor-dev \
            libbtrfs-dev \
            libcap-dev \
            libcap-ng-dev \
            libdbus-1-dev \
            libdevmapper-dev \
            libelf-dev \
            libfuse3-dev \
            libglib2.0-dev \
            libgnutls28-dev \
            libgpgme-dev \
            libjson-glib-dev \
            libnet1-dev \
            libnl-3-dev \
            libnuma-dev \
            libpam0g-dev \
            libpixman-1-dev \
            libpng-dev \
            libprotobuf-c-dev \
            libprotobuf-dev \
            librbd-dev \
            libseccomp-dev \
            libselinux1-dev \
            libspice-server-dev \
            libsqlite3-dev \
            libssl-dev \
            libsystemd-dev \
            libtirpc-dev \
            libtool \
            libudev-dev \
            libusb-1.0-0-dev \
            libusbredirhost-dev \
            libuv1-dev \
            lsb-release \
            mtools \
            ninja-build \
            pkg-config \
            protobuf-c-compiler \
            protobuf-compiler \
            python3-cryptography \
            python3-jinja2 \
            python3-pexpect \
            python3-pip \
            python3-setuptools \
            python3-venv \
            rsync \
            socat \
            uuid-dev \
            xmlto \
            xorriso

          apt-get install --no-install-recommends --yes systemd-dev || true

          pip3 install meson || pip3 install meson --break-system-packages
          pip3 install tomli || pip3 install tomli --break-system-packages

      - name: Install Go
        run: |
          curl -sL "https://go.dev/dl/${GOLANG_TAG}.linux-${OS_ARCH}.tar.gz" | tar -C /usr/local/ -zx
          go version

      - name: Install Rust
        run: |
          curl -sL https://sh.rustup.rs -o install-rust.sh
          bash install-rust.sh -y

      - name: Install Node
        run: |
          [ "${OS_ARCH}" = "amd64" ] && NODE_ARCH=x64
          [ "${OS_ARCH}" = "arm64" ] && NODE_ARCH=arm64


          mkdir /usr/local/node/
          curl -sL "https://nodejs.org/dist/v22.11.0/node-v22.11.0-linux-${NODE_ARCH}.tar.xz" | tar -C /usr/local/node/ -Jx --strip-components=1

      - name: Build environment
        run: |
          mkdir /build/
          mkdir -p \
            /opt/incus/bin/ \
            /opt/incus/include/ \
            /opt/incus/lib/ \
            /opt/incus/lib/systemd \
            /opt/incus/share/

      - name: Get the code
        run: |
          git clone https://github.com/lxc/distrobuilder /build/distrobuilder --depth 1 -b "${DISTROBUILDER_TAG}"
          git clone https://github.com/lxc/lxc /build/lxc -b "${LXC_TAG}"
          git clone https://github.com/lxc/lxcfs /build/lxcfs --depth 1 -b "${LXCFS_TAG}"
          git clone https://github.com/lxc/incus /build/incus -b "${INCUS_TAG}"
          git clone https://github.com/zabbly/incus-ui-canonical /build/incus-ui-canonical --depth 1 -b "${INCUS_UI_CANONICAL_TAG}"

          git clone https://github.com/axboe/liburing /build/liburing --depth 1 -b "${LIBURING_TAG}"
          git clone https://github.com/checkpoint-restore/criu /build/criu --depth 1 -b "${CRIU_TAG}"
          git clone https://github.com/containers/skopeo /build/skopeo --depth 1 -b "${SKOPEO_TAG}"
          git clone https://github.com/cowsql/cowsql /build/cowsql --depth 1 -b "${COWSQL_TAG}"
          git clone https://github.com/cowsql/raft /build/raft --depth 1 -b "${RAFT_TAG}"
          git clone https://github.com/go-acme/lego /build/lego --depth 1 -b "${LEGO_TAG}"
          git clone https://github.com/minio/mc /build/mc --depth 1 -b "${MINIO_MC_TAG}"
          git clone https://github.com/minio/minio /build/minio --depth 1 -b "${MINIO_TAG}"
          git clone https://github.com/NVIDIA/libnvidia-container /build/libnvidia-container --depth 1 -b "${NVIDIA_CONTAINER_TAG}"
          git clone https://github.com/stefanberger/libtpms /build/libtpms --depth 1 -b "${LIBTPMS_TAG}"
          git clone https://github.com/stefanberger/swtpm /build/swtpm --depth 1 -b "${SWTPM_TAG}"
          git clone https://github.com/tianocore/edk2 /build/edk2 --recurse-submodules --shallow-submodules --depth 1 -b "${EDK2_TAG}"
          git clone https://github.com/truenas/truenas_incus_ctl /build/truenas_incus_ctl --depth 1 -b "${TRUENAS_INCUS_CTL_TAG}"
          git clone https://gitlab.com/qemu-project/qemu /build/qemu --depth 1 -b "${QEMU_TAG}"
          git clone https://gitlab.com/qemu-project/seabios /build/seabios --depth 1 -b "${SEABIOS_TAG}"
          git clone https://gitlab.com/virtio-fs/virtiofsd /build/virtiofsd --depth 1 -b "${VIRTIOFSD_TAG}"

          mkdir /build/nasm/
          curl -sL "https://www.nasm.us/pub/nasm/releasebuilds/$(echo ${NASM_TAG} | cut -d- -f2)/${NASM_TAG}.tar.gz" --resolve www.nasm.us:443:198.137.202.136 | tar -C /build/nasm/ -zx --strip-components=1

      - name: Build liburing
        run: |
          cd /build/liburing
          ./configure --prefix=/opt/incus
          make

          mkdir -p /build/target/liburing/
          DESTDIR=/build/target/liburing make install
          rsync -a /build/target/liburing/opt/incus/include/* /opt/incus/include/
          rsync -a /build/target/liburing/opt/incus/lib/* /opt/incus/lib/

      - name: Build raft
        run: |
          cd /build/raft
          autoreconf -i
          ./configure --prefix=/opt/incus
          make

          mkdir -p /build/target/raft/
          DESTDIR=/build/target/raft/ make install
          rsync -a /build/target/raft/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/raft/opt/incus/lib/ /opt/incus/lib/

      - name: Build cowsql
        run: |
          cd /build/cowsql
          autoreconf -i
          ./configure --prefix=/opt/incus
          make

          mkdir -p /build/target/cowsql/
          DESTDIR=/build/target/cowsql/ make install
          rsync -a /build/target/cowsql/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/cowsql/opt/incus/lib/ /opt/incus/lib/

      - name: Build LXC
        run: |
          REPO="${PWD}"

          cd /build/lxc

          meson setup build \
                  --prefix=/opt/incus \
                  --libdir=/opt/incus/lib \
                  -Dexamples=false \
                  -Dman=false \
                  -Dtools=false \
                  -Dtests=false \
                  -Dmemfd-rexec=false \
                  -Dapparmor=true \
                  -Dseccomp=true \
                  -Dselinux=true \
                  -Dcapabilities=true \
                  -Dio-uring-event-loop=false
          meson compile -C build

          mkdir -p /build/target/lxc/
          DESTDIR=/build/target/lxc/ meson install -C build
          rsync -a /build/target/lxc/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/lxc/opt/incus/lib/ /opt/incus/lib/
          mkdir -p /opt/incus/share/lxc/config/common.conf.d/
          mkdir -p /opt/incus/share/lxc/hooks/
          cp /build/target/lxc/opt/incus/share/lxc/hooks/nvidia /opt/incus/share/lxc/hooks/

      - name: Build LXCFS
        run: |
          REPO="${PWD}"

          cd /build/lxcfs
          meson setup build \
                  --prefix=/opt/incus \
                  --libdir=/opt/incus/lib \
                  -Ddocs=false \
                  -Dtests=false
          meson compile -C build

          mkdir -p /build/target/lxcfs/
          DESTDIR=/build/target/lxcfs/ meson install -C build
          rsync -a /build/target/lxcfs/opt/incus/bin/ /opt/incus/bin/
          rsync -a /build/target/lxcfs/opt/incus/share/ /opt/incus/share/
          rsync -a /build/target/lxcfs/opt/incus/lib/ /opt/incus/lib/

          sed -i "s#/var/lib/lxcfs#/var/lib/incus-lxcfs#g" /opt/incus/share/lxcfs/lxc.mount.hook
          patch -p1 /opt/incus/share/lxcfs/lxc.mount.hook < "${REPO}/patches/lxcfs-0001-hook.patch"

      - name: Build Incus
        run: |
          REPO="${PWD}"

          cd /build/incus

          git cherry-pick 12dda5c91a8257a4f8ffb347751d64e60d332636  # shared/cliconfig: Shorten path to using keepalive proxy
          git cherry-pick ff17bc7c7862b8a669a8771e381bebab3ef289e7  # shared/cliconfig: Implement TLS cert/key/ca caching
          git cherry-pick 5068001c23a0bfa2cfa66a9d2ccb064d49d8d847  # shared/cliconfig: Add support for encrypted TLS keys to keepalive proxy
          git cherry-pick c9c054f6d5bad5d9c4c43f0df79822a069e279e1  # client: Optionally skip blocking for OIDC authentication
          git cherry-pick 7144a9f7ffe9fdfeb80e524fddb4ce78ebbed8f4  # incus/version: Gracefully fail when server unreachable
          git cherry-pick ad80c08869115e774484a1d1db864b612d183878  # incusd/instance/agent-loader: Use Linux arch names
          git cherry-pick 0ad430455f485d37660fc2d1b3f03335885114d4  # incusd/instance/qmp: Add QuerySpice
          git cherry-pick 72d84b95163d3be8689f13ded891000588749c41  # incusd/instance/qemu: Add SPICE detection logic
          git cherry-pick e8797236277969dacb51a58cd1ca8eccd3eedde2  # incusd/instance/qemu: Disable SPICE on systems missing support
          git cherry-pick 59bcf3c8b8df7a0657309a987e0e02504a0a755a  # incusd/instances/qemu: Rework qemuArchConfig
          git cherry-pick 182a89bb2826a6d844780f61522432d57b44ff31  # incusd/instance/qmp: Add Query9pDevice
          git cherry-pick 6b2bbb0148eb037838076ffb3d82f17c853bc69a  # incusd/instance/qemu: Add plan9 detection logic
          git cherry-pick 1143820ebdcd9ed3e9a7e3ec1b99ab242256919c  # incusd/instance/qemu: Export plan9 drives only when supported
          git cherry-pick 60cc2aacbbc3f99d8e4525224f582465c3408356  # incusd/instance/qemu: enable SPICE audio via feature gate
          git cherry-pick c95f5ba529fd57eada628d7ee10299f5f5200b86  # incusd: Fix bad type in format strings
          git cherry-pick f305f8fdd5a3899a1d37ddf6ed4dd72d72affbbf  # incusd/instance/qmp: Add QueryVirtioSoundDevice
          git cherry-pick 9d5c86f4f122ad80ab4d67bd7ffedd7d380890f8  # incusd/instance/qemu: Add virtio-sound detection logic
          git cherry-pick 204c0fa52f548015d47f1caac619ee083f8fcb85  # incusd/instance/qemu: Omit audio device on systems without virtio-sound
          git cherry-pick e0ade0dfc5cfd20abd9c7a99fd3e0618b8bc3a90  # incusd/storage: Delete dependent volumes on instance deletion
          git cherry-pick 42653279acb5652b391273508a13648c0bb4d667  # tests: Test dependent volume deletion on instance deletion
          git cherry-pick 0c0fd0e32929d9877bf647892128b91f27a6e5b8  # internal/incusos: Allow non-GET requests
          git cherry-pick 312ba9f57187ad7ebc3837ba0b8c9f3cd34c8813  # internal/incusos: Implement TriggerSystemUpdateCheck
          git cherry-pick 3d4a75f7c9e314d4ebd2fe468d6eafb5e10b4747  # incusd: Trigger IncusOS update check on version mismatch
          git cherry-pick 33fa8fe83bed5188d4b28a2d29ee6946e703a560  # incusd/response: Make pipeResponse flush headers ASAP
          git cherry-pick 2f3b0f04c6d712a78f5a542e9799873a215ba894  # incusd: Disallow setting the 'dependent' key on volume creation
          git cherry-pick ff71fe4423bf1386a205d083154d9e3f9d4802e1  # incusd/device: Update 'dependent' flag on device add and detach
          git cherry-pick f7f600b2d20ee649fca3e7643e6cf7afa232b3a2  # tests: Add additional tests for dependent volume handling
          git cherry-pick 71b33fb57be320dd1ab4c957749699a408485015  # incusd/instance/common: Don't perform costly storage actions when no snapshots
          git cherry-pick 77d89e32eb21e8fc77f933409e4c5b105f78f6bc  # incusd: Remove explicit caching mechanism in favor of implicit
          git cherry-pick 5d05e18a870fcdcaf6f33576afe37216d5214133  # incusd/storage/zfs: Implement better caching
          git cherry-pick ac805fc4a0c2a09c7b21532172212fa4feb06804  # incusd/storage/truenas: Implement better caching
          git cherry-pick 568bca413fd60873682bd4c7f220ef7cff2e7568  # incusd/instances: Allow more concurency
          git cherry-pick 8c8733af634ccbb3c021650ad26662130c1e38a2  # incusd/storage/truenas: Retry iSCSI map request
          git cherry-pick c37b9bf7ccbd63e5d4658eb6cd9f92fdc2955161  # shared/cliconfig: Avoid treating `=` as part of a remote name
          git cherry-pick 17e857533e03fcd5bb270efd5a9e5a33f8aa5ea6  # incusd/network/state: Use canAccessNetwork
          git cherry-pick dfc98eeaf3745382c0870dd679078e5260eb3d2b  # incusd/storage/truenas: Use old-style ZFS types
          git cherry-pick ac893aecc34e4dfe429008917925e6d6379c03ed  # incusd/storage/zfs: Use old-style ZFS types
          git cherry-pick 0fae4ba67c978de1ea4740d1532718d5742f7317  # shared/api: Switch to go-yaml/v4
          git cherry-pick a74d566c0f0f64d7d87f106421de8712d6133399  # shared/cliconfig: Switch to go-yaml/v4
          git cherry-pick cda3ac59b76ecdaa9b93c6b9ab301ecd6fc0c59e  # shared/cmd: Switch to go-yaml/v4
          git cherry-pick 28e767d808d6ff71bab2cbc6bb4fac8cd36174cc  # shared/subprocess: Switch to go-yaml/v4
          git cherry-pick 9f8574a71a005cf3308c0459d843a691ba20f3a3  # shared/validate: Switch to go-yaml/v4
          git cherry-pick de27e44be9f986e858d0942606b9703760565fc2  # incusd/instance/drivers: Switch to go-yaml/v4
          git cherry-pick fa3a8d4ddc93e880712dd86794f4257cd005393d  # incusd/storage: Switch to go-yaml/v4
          git cherry-pick 39a18a73b30299ca7cfc0ea2486e728bfa0363c0  # incus-agent: Switch to go-yaml/v4
          git cherry-pick 7a8c6aea461ef67b72307d9eb33671d375a40623  # incus-migrate: Switch to go-yaml/v4
          git cherry-pick 20a8c5e06a86290a078e8b43df1329ffdf09ad66  # incus-simplestreams: Switch to go-yaml/v4
          git cherry-pick b73a1fe4c2546ae524810b0b7a10b590aa3ff269  # incusd/backup: Switch to go-yaml/v4
          git cherry-pick 3d178e135ed83ff767272cdd74c0d8c91c34c3ee  # incusd/storage/drivers: Switch to go-yaml/v4
          git cherry-pick 0adef7322791db7343eb16dea27572ffb34e5072  # incusd: Switch to go-yaml/v4
          git cherry-pick 4b69bf2db71a2600b74652197f18d05dbcebdeb9  # incus: Switch to go-yaml/v4
          git cherry-pick 853f96f9d24bb09b68d3d62a16f5a5c3976796b8  # test: Switch to go-yaml/v4
          git cherry-pick a996d03ae7cd3ae9b1ac0cac6d717fe5ab1a6fa7  # gomod: Update dependencies
          git cherry-pick 81044dc52babaedbcea2f0e7b48bd88456d1b474  # incus: Update for new YAML empty reader behavior
          git cherry-pick 271cd4cf0cee01bce9cee4a51f459923ccd0ca0a  # test: Fix ordering of godeps.list
          git cherry-pick e69aba01fb747d4b5305dd3766dccb92a477408f  # tests: Update for slight YAML differences
          git cherry-pick bca9d223dfd373bd7914f739f4d4a7ce83f4909d  # incusd/device: Ignore 'not found' errors when updating dependent config during device add/remove
          git cherry-pick 8f8fc283537bd356262175581fa3e1a8a4989095  # incusd/storage: Add ShouldMigrateDependentVolume
          git cherry-pick d2af510ecb1120354e36cbd3b2cf33d63a67b452  # incusd/instance: Add support for disk name to ExportQcow2Block
          git cherry-pick 372818c855b59a943fa5e67c0ab237f070a7a4af  # incusd/instance/drivers: Add support for cross-cluster dependent volumes migration
          git cherry-pick c25590ea55115ae7a1cb8f663963919dec4dc1d9  # incusd/storage: Add support for cross-cluster dependent volumes migration
          git cherry-pick a223c01b8ff6f2c218d76aaabd300888d23c0a3f  # incusd/instance: Add HasDependentDisk and ForEachDependentDiskType to instance interface
          git cherry-pick 43d86bef5f7e9a9ac60f5f29348e9caac2af3b57  # incusd/storage: use ForEachDependentDiskType and HasDependentDisk from instance
          git cherry-pick 6573e9bc75eb1488d9799201e31d2e0f32c4c261  # incusd/instance: Pass additional parameter to Delete method
          git cherry-pick beed5b58807bbc8dbe1035c1061ae94a159b0713  # incusd/storage: Pass additional parameter to Delete method
          git cherry-pick 95b7619231066934726b89b6557966689caaf542  # incusd/instance: Move dependent volume deletion from storage to instance delete()
          git cherry-pick a1d3f28c939235d2ed710ab57e46718b6784b91e  # incusd/storage: Move dependent volume deletion from storage to instance delete()
          git cherry-pick 41589e8368ca953e6da8794cd13e5980d280c06a  # incusd/storage: Fix race in caching logic
          git cherry-pick 913dd148242583fba1f95496c6395d4a55b7796a  # incusd/storage: Fix potential deadlock
          git cherry-pick d84ed053de7ad8514fa81e84021b32f3a420e574  # incusd/migration: Implement cancelation in migration logic
          git cherry-pick ea8289d960cde163f46954b6de1a5ad39f859d22  # incusd/instances: Implement cancelation in exec logic
          git cherry-pick 9c4945c2b4aefe0c0caa40faf85fd430a36af6b3  # incusd: Clarify shutdown message
          git cherry-pick 617d880282c5c9e9cbbbeac382288261e2372709  # incusd/instance: Rename deleteDependentVolumes to cleanupDependencies
          git cherry-pick 40a7bbae08acb39524e3202a8761d5a23a2adb4d  # incus/server/network/ovn/nb: Add function to get PortGroups by Port UUID
          git cherry-pick 65a56f4e33d39688bf94976168a90d9f3947f4f0  # incus/server/network/ovn/driver: Cleanup stale instance port uuids from acl port groups on instance stop
          git cherry-pick 07faf5e0bb1f0263fe2d5a614eb6d66ea509eb59  # incusd/storage: Support optimized storage for dependent volumes
          git cherry-pick 068dce801c500384b95c4d653c7970e5670162ff  # incusd/storage: Improve logging during dependent volume creation from backup
          git cherry-pick 1ea73e37b86521a17d03f4b336b5536affb00d95  # incusd/storage: Rename createDependentVolumes to createDependentVolumesFromBackup
          git cherry-pick 58fd96a51c99ace38e2fd6942c349d6f5643f492  # incusd/device: Add cleanupDependencies argument to Remove() method
          git cherry-pick 68d6be36e5ea32f615c31d3c3899d2251d116b88  # incusd/instance/drivers: Pass the cleanupDependencies flag to device Remove
          git cherry-pick 672189f1014df0ba7f899afe9faca4ff4da5dc60  # incusd/storage: Improve comments on locks
          git cherry-pick 2889445b3bbd399e03dffafe90e116b9d2580d13  # incusd/forksyscall: Handle mount arguments when using idmap
          git cherry-pick 142e03b80f866b0abc92624855cc9b095b69e467  # incusd/storage: Use device name when importing dependent volumes from backup
          git cherry-pick b84add734530e4ba6e06ae110d6f7e7e48a79f6a  # tests: Add tests for exporting/importing dependent volumes
          git cherry-pick 644d69d7f303327c444c55e3244d07a272a87614  # incusd/cluster/config: Clarify description of oidc.claim option
          git cherry-pick 3777a484e4993e9773b7f9ea82dae6ccb988d888  # doc: Update metadata
          git cherry-pick 880c84caab6129f99d1c9c9834b40f77ced7618e  # incusd/device/nic_physical: Fix device validation
          git cherry-pick 39eef97658213c4df17b8fbec6b6bafa92f80037  # doc: Update config
          git cherry-pick b29ab524b38d2475858792a702a1878b8348e8a3  # incusd/instance: Add support for stateful snapshots for qcow2 volumes
          git cherry-pick d71c370445b27a474652faf762a435734e259c4a  # incusd/storage: Add support for stateful snapshots for qcow2 volumes
          git cherry-pick eefd6f880126519339dfe7a9e97c5db10cb1dc63  # incusd: Don't expose the API extension list pre-authentication
          git cherry-pick 2259e714e41eeecb6e2f74ca08464fc2bc79f1da  # incusd/device/nic_physical: Fix bridge handling
          git cherry-pick 974eb2b8a38a7c333229bcde3b178a8569a37f20  # incusd/device/nic_physical: Fix inheritance from network
          git cherry-pick ee5d142bf1a34e4d8f078cea1ff316b2fe720ae9  # incusd/instances/qemu: Skip vmcoreinfo on ppc64le
          git cherry-pick 7f4c5832053227a8e0df8e5e93ddb2afe0b90f8a  # incusd/device/nic_bridged: Handle physical NICs
          git cherry-pick a001d5e8dd9e8c5c889114b1992e149c829e0373  # incusd/instance/drivers: Fix live migration of instances with snapshots
          git cherry-pick 9d4f3b77065bba94a01a2bcb924db7ce0f9d755d  # incusd/instance/qemu: Scale SCSI queues with CPUs
          git cherry-pick 8babda1d90d35a049086f57c4892702c1dc9dbb3  # incus: Enable admin recover and admin sql on all platforms
          git cherry-pick 89f54836630fbd40367d737178f9f093fe5da1ae  # client: Forward skopeo errors
          git cherry-pick 17ce1b91c3bc62b05d20be5118fdf6197c1a2b0a  # incusd/storage: Add instanceStateful flag to volume snapshot operations
          git cherry-pick 13f4389fa3adc939008efe19564426a203ba1403  # incusd/device: Pass instanceStateful flag during instance snapshot
          git cherry-pick cb0dc427b00553443b3f20d33b4a5d90d9699445  # incusd: Pass instanceStateful flag during instance snapshot
          git cherry-pick 629047c3f8a91d0f8f3007629d71fbd03cd76fa1  # incusd/apparmor/qemuimg: Expand symlinks
          git cherry-pick b67d5b8ab726701b781d00363e26880f6f7b92fd  # incus: Fix Windows absolute paths
          git cherry-pick f8ec5611ab0cad849a94ef1006adf309e57a006c  # incus: Enforce stricter directory checks
          git cherry-pick aac4f8a206ca3ff142b41c55b2ae97411ee7fd53  # tests: Add strict pull checks for directories
          git cherry-pick d5bc02c0040c080fc16ab5edd2dfd39eec8921e4  # incusd/instance/qemu: Fix RTC handling on Windows
          git cherry-pick 18d1e53dc26c99e3379f136aff212e83fda28fc1  # incusd/storage/drivers: Fix ordering in Qcow2DeletionCleanup
          git cherry-pick 99cc09c7bdd66831e3ec7aa5b0d9292501cb4164  # incusd/instance/drivers: Improve snapshot creation rollback handling
          git cherry-pick f272bb3566289f357e7bc51a893b1660ffacbf6f  # incusd/storage: Improve snapshot creation rollback handling
          git cherry-pick 26227cae3c23be2c1dc862d419b95ab7ee020861  # internal/instance: Introduce volatile.vm.boot_state
          git cherry-pick ee5cb850deda229cc95314b2cfe60fa493a4ccaf  # incusd/instance/qemu: Rename internal structs
          git cherry-pick 1f8037877f690d1a0db25fa5655357cb9d4a16da  # incusd/instance/qemu: Add new migration state volatile
          git cherry-pick 0c0a3ddfb4b65f452ce8ecfe7c5f5ff9126a0c8d  # incusd/instance/qemu: Move topology functions to new file
          git cherry-pick a4aed86f01d2f47baa0a363f8c28725231355d13  # incusd/instance/qemu: Make use of new migration state logic
          git cherry-pick a59ad82ebad2df63ef804f6c9497d8080da7d38a  # incusd/instance/qemu: Don't export internal vcpus and numa nodes maps
          git cherry-pick 2826d1ae9c5f57e5cb5f49df8a24662a31c10270  # doc: Update config
          git cherry-pick 69255206c7d54506c57f40f28526a84ee4ace697  # incusd/instance/qemu: Handle stateful detection corner case
          git cherry-pick bed4cd20f6930342db9374432252cec1ad7308f8  # incusd/migrate: Set short timeouts on read/write of control data
          git cherry-pick c9d51c46674ee296010f03b54775caddb0dc0318  # client: Fix bad error handling
          git cherry-pick 7f9535fa31cc07af7e102e6a19576dbea980538a  # incusd/response/upgrade: Add small delay for NBD
          git cherry-pick 91868e4366bd10cbf33aff06ef298e252697bab9  # incus/server/network/ovn/nb: Mark route as discord when nexthop is 'discard'
          git cherry-pick 8f7b2a2145e48f86e2f83f1547d9c4afc8cadcd1  # incus/server/network/ovn/driver: Only add discard route if it doesn't exist already
          git cherry-pick 62cda5636b79a32a67ce9bee240ddee35fe564e4  # incusd/storage: Improve qcow2 volume handling
          git cherry-pick 1de0a465211f9a068e1eab051b61a9b77fd4fd43  # incusd/storage/drivers: Add syncBtrfs
          git cherry-pick d4c9dfcead3a2939a0174be25a78b996e6b368db  # incusd/storage/drivers: Use 'qemu-img info' in read-only mode
          git cherry-pick da618fb1d1610d9ab9bf58608b992829ca53f286  # incusd/instances: Don't delete ephemeral instances on system shutdown
          git cherry-pick 42278bd2b5bee46bb74937f2641b6044cf7de136  # shared/archive: Improve detection and error handling
          git cherry-pick e57a32b762abaea9f3b1defdb57f42107a03303f  # shared/subprocess: Cleanup pointless check
          git cherry-pick 4e8b6742831bc40031cc97ac1cb2cb602b81b83c  # incusd/seccomp: Cleanup pointless check
          git cherry-pick 85dc304ae8335f2827737fef905bd72c243e1a51  # incusd/migrate: Bump migration timeouts
          git cherry-pick ec50d3b37b6487b4567ea5c1a734897df79e8e6d  # incusd/migration: Bump timeouts to 30s
          git cherry-pick 9fb55bf99d209a7d294a7a06d0fc71551cfc938c  # shared/util: Introduce SafeCopy
          git cherry-pick 1396bcc735fb4b8ea2fe1bc24e855da081614284  # incusd: Switch io.CopyN to util.SafeCopy
          git cherry-pick 2614f7ff1d9644ce35962cc50db16e666780a384  # client: Switch io.Copy to util.SafeCopy
          git cherry-pick a08d2db1b536d78123faf0bcd4f8b5112c470997  # shared/ws: Switch io.Copy to util.SafeCopy
          git cherry-pick efc0c11e167aea3766f7fadfd4331630b1537733  # shared/cliconfig: Switch io.Copy to util.SafeCopy
          git cherry-pick 309a2e60b2046303d49f937dad4b1887b623bbdf  # shared/util: Switch io.Copy to util.SafeCopy
          git cherry-pick 0e6b86c210bd51f2e5fad185d6064fcad75c876b  # internal/util: Switch io.Copy to util.SafeCopy
          git cherry-pick 262451981d93aa1a7865812d1f77a650b1ec6510  # internal/io: Switch io.Copy to util.SafeCopy
          git cherry-pick 3f98917f3e367646f20ea45e3fa96dcfd3835831  # internal/rsync: Switch io.Copy to util.SafeCopy
          git cherry-pick f05bd57bd453f2c3dcc324703b5067e101132ee5  # incusd: Switch io.Copy to util.SafeCopy
          git cherry-pick 606647b8807c808571be38ce4c4d2e1acbe944a2  # incusd/instance/qemu: Fix boot state recording
          git cherry-pick f1c264a79682e308155237f3f2281d0e71abe562  # incusd/devices/disk: Lock creation of ISO images
          git cherry-pick 18e9f087927fc69d508240482591e338fa38c01d  # incusd: Increase devices tmpfs
          git cherry-pick 4777803e0656e842867b971af749ceb44f9df046  # incusd/device/nic: Prevent USB NICs on migratable VMs
          git cherry-pick 31c5e214fc75926d0e4e104cb7a5decf8e0da52f  # incusd/instance/drivers/qmp: Wait for block job completion after issuing block-job-complete
          git cherry-pick c0ea1f9520062191d96c11e1ea022bcdfff56f4a  # incusd/instance/drivers: Add support for handling BLOCK_JOB_COMPLETED and BLOCK_JOB_ERROR events
          git cherry-pick c6b9378c12892cae3f026e6b738fa809f93bfd7f  # incusd/migrate: Limit timeout to initial handshake
          git cherry-pick dc6833bbb726dee68f2816c58021971f30c4d342  # shared/archive: Avoid concurrent calls to Wait
          git cherry-pick 93a87a98b3b9f2b2e15230ff70558445d5b58dba  # incusd/storage/drivers: Extract unpackVolume and backupVolume to util
          git cherry-pick ff161e795608bde99c98af892137ff1b961bafbe  # incusd/storage/drivers: Make createParentSnapshotDirIfMissing public
          git cherry-pick ecde36d9fd8e88ecba1ee58352942ebb9998ee50  # incusd/storage: Add support for export/import qcow2 in raw format
          git cherry-pick 1de223c97691b36520a73ad7068eff3447ca832f  # incusd/instance/qemu: Improve OS detection for FreeBSD

          go build -o "/opt/incus/bin/fuidshift" github.com/lxc/incus/v6/cmd/fuidshift
          go build -o "/opt/incus/bin/incus" github.com/lxc/incus/v6/cmd/incus
          go build -o "/opt/incus/bin/incus-benchmark" github.com/lxc/incus/v6/cmd/incus-benchmark
          go build -o "/opt/incus/bin/incus-migrate" github.com/lxc/incus/v6/cmd/incus-migrate
          go build -o "/opt/incus/bin/incus-simplestreams" github.com/lxc/incus/v6/cmd/incus-simplestreams
          go build -o "/opt/incus/bin/incus-user" github.com/lxc/incus/v6/cmd/incus-user
          go build -o "/opt/incus/bin/incusd" -tags=libsqlite3 github.com/lxc/incus/v6/cmd/incusd
          go build -o "/opt/incus/bin/lxc-to-incus" github.com/lxc/incus/v6/cmd/lxc-to-incus
          go build -o "/opt/incus/bin/lxd-to-incus" -tags=libsqlite3 github.com/lxc/incus/v6/cmd/lxd-to-incus

          mkdir -p /opt/incus/agent
          if [ "$(uname -m)" = "x86_64" ]; then
              GOARCH=amd64 GOOS=darwin CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.macos.x86_64" -tags=agent,netgo github.com/lxc/incus/v6/cmd/incus-agent

              GOARCH=amd64 GOOS=freebsd CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.freebsd.x86_64" -tags=agent,netgo github.com/lxc/incus/v6/cmd/incus-agent
              GOARCH=386 GOOS=freebsd CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.freebsd.i686" -tags=agent,netgo github.com/lxc/incus/v6/cmd/incus-agent

              GOARCH=amd64 CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.linux.x86_64" -tags=agent,netgo github.com/lxc/incus/v6/cmd/incus-agent
              GOARCH=386 CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.linux.i686" -tags=agent,netgo github.com/lxc/incus/v6/cmd/incus-agent

              GOARCH=amd64 GOOS=windows CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.windows.x86_64" -tags=agent,netgo github.com/lxc/incus/v6/cmd/incus-agent
              GOARCH=386 GOOS=windows CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.windows.i686" -tags=agent,netgo github.com/lxc/incus/v6/cmd/incus-agent
          elif [ "$(uname -m)" = "aarch64" ]; then
              GOARCH=arm64 GOOS=darwin CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.macos.aarch64" -tags=agent,netgo github.com/lxc/incus/v6/cmd/incus-agent
              GOARCH=amd64 GOOS=freebsd CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.freebsd.aarch64" -tags=agent,netgo github.com/lxc/incus/v6/cmd/incus-agent
              GOARCH=arm64 CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.linux.aarch64" -tags=agent,netgo github.com/lxc/incus/v6/cmd/incus-agent
              GOARCH=arm64 GOOS=windows CGO_ENABLED=0 go build -o "/opt/incus/agent/incus-agent.windows.aarch64" -tags=agent,netgo github.com/lxc/incus/v6/cmd/incus-agent
          fi

          make build-mo
          mkdir -p /opt/incus/share/locale
          cp po/*.mo /opt/incus/share/locale/

          make doc
          cp -R doc/html /opt/incus/doc

          mkdir -p /opt/incus/share/completions/
          /opt/incus/bin/incus completion bash > /opt/incus/share/completions/bash
          /opt/incus/bin/incus completion fish > /opt/incus/share/completions/fish
          /opt/incus/bin/incus completion zsh > /opt/incus/share/completions/zsh

      - name: Build UI (canonical)
        run: |
          REPO="${PWD}"

          cd /build/incus-ui-canonical

          # Complete re-branding.
          find -type f -name "*.ts" -o -name "*.tsx" -o -name "*.scss" | xargs sed -i -f "${REPO}/patches/ui-canonical-renames.sed"

          npm install yarn --global
          yarn install
          yarn build

          mkdir -p /opt/incus/ui-canonical/
          rsync -a /build/incus-ui-canonical/build/ui/ /opt/incus/ui-canonical/

      - name: Build Distrobuilder
        run: |
          cd /build/distrobuilder
          go build -o "/opt/incus/bin/distrobuilder" github.com/lxc/distrobuilder/distrobuilder

      - name: Build CRIU
        run: |
          cd /build/criu
          make WERROR=0
          cp criu/criu /opt/incus/bin/

      - name: Build libnvidia-container
        run: |
          REPO="${PWD}"

          cd /build/libnvidia-container
          patch -p1 < "${REPO}/patches/nvidia-0001-Fix-for-22.04-build.patch"
          patch -p1 < "${REPO}/patches/nvidia-0002-pre-load-libdl.patch"
          make prefix=/

          mkdir /build/target/libnvidia-container
          DESTDIR=/build/target/libnvidia-container make install prefix=/
          rsync -a /build/target/libnvidia-container/bin/ /opt/incus/bin/
          rsync -a /build/target/libnvidia-container/include/ /opt/incus/include/
          rsync -a /build/target/libnvidia-container/lib/ /opt/incus/lib/

      - name: Build minio
        run: |
          cd /build/minio
          make build
          cp minio /opt/incus/bin/

      - name: Build minio client
        run: |
          cd /build/mc
          make build
          cp mc /opt/incus/bin/

      - name: Build seabios
        if: ${{ matrix.arch == 'amd64' }}
        run: |
          REPO="${PWD}"

          cd /build/seabios

          # Build a traditional seabios.
          make clean distclean
          echo "CONFIG_QEMU=y" > .config
          echo "CONFIG_QEMU_HARDWARE=y" >> .config
          echo "CONFIG_BOOTSPLASH=n" >> .config
          echo "CONFIG_ROM_SIZE=256" >> .config
          echo "CONFIG_XEN=n" >> .config
          echo "CONFIG_PVSCSI=n" >> .config
          echo "CONFIG_ESP_SCSI=n" >> .config
          echo "CONFIG_LSI_SCSI=n" >> .config
          echo "CONFIG_MEGASAS=n" >> .config
          echo "CONFIG_MPT_SCSI=n" >> .config
          echo "CONFIG_FLOPPY=n" >> .config
          echo "CONFIG_FLASH_FLOPPY=n" >> .config
          make oldnoconfig V=1
          make V=1 PYTHON=python3

          mkdir -p /opt/incus/share/qemu/
          cp out/bios.bin /opt/incus/share/qemu/seabios.bin

      - name: Build nasm
        run: |
          REPO="${PWD}"

          cd /build/nasm
          patch -p1 < "${REPO}/patches/nasm-0000-disable-manpages.patch"
          ./configure --prefix=/opt/incus
          make

          mkdir -p /build/target/nasm/
          DESTDIR=/build/target/nasm make install
          rsync -a /build/target/nasm/opt/incus/bin/ /opt/incus/bin/

      - name: Build EDK2
        run: |
          REPO="${PWD}"

          cd /build/edk2
          patch -p1 < "${REPO}/patches/edk2-0001-force-DUID-LLT.patch"
          cp "${REPO}/patches/edk2-0002-logo.bmp" MdeModulePkg/Logo/Logo.bmp
          patch -p1 < "${REPO}/patches/edk2-0003-boot-delay.patch"
          patch -p1 < "${REPO}/patches/edk2-0004-gcc-errors.patch"
          patch -p1 < "${REPO}/patches/edk2-0005-Revert-ArmVirtPkg-make-EFI_LOADER_DATA-non-executabl.patch"
          patch -p1 < "${REPO}/patches/edk2-0006-disable-EFI-memory-attributes-protocol.patch"
          patch -p1 < "${REPO}/patches/edk2-0007-OvmfPkg-X64-add-opt-org-tianocore-UninstallMemAttrProtocol-support.patch"
          patch -p1 < "${REPO}/patches/edk2-0008-Disable-virtio-keyboard.patch"
          patch -p1 < "${REPO}/patches/edk2-0009-fix-esxi-usb.patch"
          patch -p1 < "${REPO}/patches/edk2-9999-disable-UEFI-shell-under-SecureBoot.patch"

          sed -i "s#02/02/2022#$(date +%m/%d/%Y)#g" OvmfPkg/SmbiosPlatformDxe/SmbiosPlatformDxe.c

          EDK2_ARCH="X64"
          EDK2_PKG="OvmfPkg/OvmfPkgX64.dsc"
          EDK2_FV_CODE="OVMF_CODE"
          EDK2_FV_VARS="OVMF_VARS"
          if [ "$(uname -m)" = "aarch64" ]; then
              EDK2_ARCH="AARCH64"
              EDK2_PKG="ArmVirtPkg/ArmVirtQemu.dsc"
              EDK2_FV_CODE="QEMU_EFI"
              EDK2_FV_VARS="QEMU_VARS"
          fi

          build_edk2() {
              TARGET_CODE="$1"
              shift
              TARGET_VARS="$1"
              shift

              set -ex
              (
              cat << EOF
                  . ./edksetup.sh
                  make -C BaseTools ARCH=${EDK2_ARCH}
                  build -a ${EDK2_ARCH} -t GCC5 -b RELEASE -p ${EDK2_PKG} \
                    -DSMM_REQUIRE=TRUE \
                    -DSECURE_BOOT_ENABLE=TRUE \
                    -DNETWORK_IP4_ENABLE=TRUE \
                    -DNETWORK_IP6_ENABLE=TRUE \
                    -DNETWORK_TLS_ENABLE=TRUE \
                    -DNETWORK_HTTP_BOOT_ENABLE=TRUE \
                    -DTPM2_ENABLE=TRUE \
                    -DTPM2_CONFIG_ENABLE=TRUE \
                    --pcd PcdUninstallMemAttrProtocol=TRUE \
                    $@
          EOF
              ) | bash -e

              cp Build/*/*/FV/${EDK2_FV_CODE}.fd "${TARGET_CODE}"
              cp Build/*/*/FV/${EDK2_FV_VARS}.fd "${TARGET_VARS}"

              if [ "$(uname -m)" = "aarch64" ]; then
                  truncate -s 64m "${TARGET_CODE}"
                  truncate -s 64m "${TARGET_VARS}"
              fi
          }

          mkdir -p "/opt/incus/share/qemu/"
          build_edk2 \
            "/opt/incus/share/qemu/OVMF_CODE.4MB.fd" \
            "/opt/incus/share/qemu/OVMF_VARS.4MB.fd" \
            -DFD_SIZE_4MB

          ln -s OVMF_CODE.4MB.fd /opt/incus/share/qemu/OVMF_CODE.fd
          ln -s OVMF_VARS.4MB.fd /opt/incus/share/qemu/OVMF_VARS.fd

      - name: Build libtmps
        run: |
          cd /build/libtpms
          ./autogen.sh
          ./configure --prefix=/opt/incus --with-tpm2 --with-openssl
          make

          mkdir -p /build/target/libtpms/
          DESTDIR=/build/target/libtpms make install
          rsync -a /build/target/libtpms/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/libtpms/opt/incus/lib/ /opt/incus/lib/

      - name: Build swtpm
        run: |
          cd /build/swtpm
          ./autogen.sh
          ./configure --prefix=/opt/incus --with-seccomp --with-openssl --without-cuse
          make

          mkdir -p /build/target/swtpm/
          DESTDIR=/build/target/swtpm make install
          rsync -a /build/target/swtpm/opt/incus/bin/ /opt/incus/bin/
          rsync -a /build/target/swtpm/opt/incus/include/ /opt/incus/include/
          rsync -a /build/target/swtpm/opt/incus/lib/ /opt/incus/lib/

      - name: Build virtiofsd
        run: |
          cd /build/virtiofsd
          cargo build --release
          cp target/release/virtiofsd /opt/incus/bin/

      - name: Build lego
        run: |
          cd /build/lego
          go build -o "/opt/incus/bin/lego" github.com/go-acme/lego/v4/cmd/lego

      - name: Build skopeo
        run: |
          cd /build/skopeo
          go build -o "/opt/incus/bin/skopeo" github.com/containers/skopeo/cmd/skopeo

      - name: Build TrueNAS Incus CTL
        run: |
          REPO="${PWD}"

          cd /build/truenas_incus_ctl

          patch -p1 < "${REPO}/patches/truenas-0001-bump-timeouts.patch"

          go build -o "/opt/incus/bin/truenas_incus_ctl" truenas/truenas_incus_ctl

      - name: Build QEMU
        run: |
          REPO="${PWD}"

          cd /build/qemu

          sed -i "s/^unset target_list$/target_list=\"$(uname -m)-softmmu\"/" configure

          sed -i "/subdir('tests')/d" meson.build
          ./configure \
                  --prefix=/opt/incus \
                  --libexecdir=bin \
                  --libdir=lib \
                  --disable-bochs \
                  --disable-cloop \
                  --disable-dmg \
                  --disable-docs  \
                  --disable-fuse  \
                  --disable-guest-agent \
                  --disable-parallels \
                  --disable-qed \
                  --disable-slirp \
                  --disable-user \
                  --disable-vdi \
                  --disable-vnc \
                  --disable-xen \
                  --disable-install-blobs \
                  --enable-attr \
                  --enable-cap-ng \
                  --enable-kvm \
                  --enable-libusb \
                  --enable-usb-redir \
                  --enable-linux-aio \
                  --enable-linux-io-uring \
                  --enable-numa \
                  --enable-pie \
                  --enable-png \
                  --enable-rbd \
                  --enable-seccomp \
                  --enable-spice \
                  --enable-system \
                  --enable-tcg \
                  --enable-tools \
                  --enable-vhost-crypto \
                  --enable-vhost-kernel \
                  --enable-vhost-net \
                  --enable-vhost-user \
                  --enable-virtfs
          make

          mkdir /build/target/qemu/
          DESTDIR=/build/target/qemu/ make install
          rsync -a /build/target/qemu/opt/incus/bin/ /opt/incus/bin/
          rsync -a /build/target/qemu/opt/incus/lib/ /opt/incus/lib/
          rsync -a /build/target/qemu/opt/incus/share/qemu/ /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/kvmvapic.bin /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/vgabios-qxl.bin /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/vgabios-virtio.bin /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/efi-e1000e.rom /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/efi-virtio.rom /opt/incus/share/qemu/
          cp /build/qemu/pc-bios/efi-vmxnet3.rom /opt/incus/share/qemu/

      - name: Build Secure Boot firmware
        run: |
          REPO="${PWD}"

          cd /build/edk2

          FIRMWARE="OVMF"
          if [ "$(uname -m)" = "aarch64" ]; then
            FIRMWARE="AAVMF"
          fi

          cd "${REPO}/edk2-vars-generator"
          ./edk2-vars-generator -f "${FIRMWARE}" \
            -e /build/edk2/Build/*/*/*/EnrollDefaultKeys.efi \
            -s /build/edk2/Build/*/*/*/Shell.efi \
            -c "/opt/incus/share/qemu/OVMF_CODE.4MB.fd" \
            -V "/opt/incus/share/qemu/OVMF_VARS.4MB.fd" \
            -C "$(cat ${REPO}/zabbly-sb.oem.crt)" \
            -o "/opt/incus/share/qemu/OVMF_VARS.4MB.ms.fd"

      - name: Strip and cleanup binaries
        run: |
          rm -Rf /opt/incus/lib/debug/
          rm -Rf /opt/incus/include/
          rm -Rf /opt/incus/lib/pkgconfig/
          rm /opt/incus/lib/*.a /opt/incus/lib/*.la /opt/incus/lib/*/*.a /opt/incus/lib/*/*.la

          rm /opt/incus/bin/nasm
          rm /opt/incus/bin/ndisasm
          rm /opt/incus/bin/qemu-bridge-helper
          rm /opt/incus/bin/qemu-edid
          rm /opt/incus/bin/qemu-io
          rm /opt/incus/bin/qemu-pr-helper
          rm /opt/incus/bin/qemu-storage-daemon
          rm /opt/incus/bin/swtpm_*
          rm /opt/incus/share/qemu/trace-events-all

          strip /opt/incus/agent/*linux*
          strip /opt/incus/bin/*
          strip /opt/incus/lib/*so*

      - name: Make a Debian package
        env:
          PKGOS: ${{ matrix.os }}
        run: |
          [ "${PKGOS}" = "debian-11" ] && CODENAME=bullseye
          [ "${PKGOS}" = "debian-12" ] && CODENAME=bookworm
          [ "${PKGOS}" = "debian-13" ] && CODENAME=trixie
          [ "${PKGOS}" = "ubuntu-22.04" ] && CODENAME=jammy
          [ "${PKGOS}" = "ubuntu-24.04" ] && CODENAME=noble

          mkdir -p \
            pkg/ \
            pkg/etc \
            pkg/lib/systemd/system/ \
            pkg/opt/ \
            pkg/usr/bin/ \
            pkg/usr/lib/sysctl.d/ \
            pkg/usr/share/bash-completion/completions/ \
            pkg/usr/share/fish/vendor_completions.d/ \
            pkg/usr/share/zsh/vendor-completions/

          cp -R debian pkg/debian
          cp -R bin/* pkg/usr/bin/
          cp -R /opt/incus pkg/opt/
          cp -R etc/* pkg/etc/

          cp -R systemd/system/* pkg/lib/systemd/system/
          cp -R systemd/wrappers/* pkg/opt/incus/lib/systemd/
          cp -R systemd/sysctl.d/* pkg/usr/lib/sysctl.d/

          ln -s /opt/incus/share/completions/bash pkg/usr/share/bash-completion/completions/incus
          ln -s /opt/incus/share/completions/fish pkg/usr/share/fish/vendor_completions.d/incus.fish
          ln -s /opt/incus/share/completions/zsh pkg/usr/share/zsh/vendor-completions/_incus

          ln -s /opt/incus/bin/fuidshift pkg/usr/bin/fuidshift
          ln -s /opt/incus/bin/incus-simplestreams pkg/usr/bin/incus-simplestreams
          ln -s /opt/incus/bin/incus-benchmark pkg/usr/bin/incus-benchmark

          mkdir -p pkg/var/lib/incus
          chmod 711 pkg/var/lib/incus

          mkdir -p pkg/var/log/incus
          chmod 700 pkg/var/log/incus

          mkdir -p pkg/usr/share/locale
          for i in /opt/incus/share/locale/*.mo; do
            LANG=$(echo $i | sed -e "s#.*/locale/##g" -e "s#.mo\$##g")
            mkdir -p pkg/usr/share/locale/${LANG}/LC_MESSAGES
            ln -s ${i} pkg/usr/share/locale/${LANG}/LC_MESSAGES/incus.mo
          done

          cd pkg

          if [ "${PKGOS}" = "debian-13" ] || [ "${PKGOS}" = "ubuntu-24.04" ]; then
            sed -i debian/control \
              -e "s/LIBPNG16/libpng16-16t64/g" \
              -e "s/LIBUSBREDIRPARSER1/libusbredirparser1t64/g" \
              -e "s/LIBAIO1/libaio1t64/g" \
              -e "s/LIBBTRFS0/libbtrfs0t64/g" \
              -e "s/LIBGPGME11/libgpgme11t64/g" \
              -e "s/LIBUV1/libuv1t64/g"
          else
            sed -i debian/control \
              -e "s/LIBPNG16/libpng16-16/g" \
              -e "s/LIBUSBREDIRPARSER1/libusbredirparser1/g" \
              -e "s/LIBAIO1/libaio1/g" \
              -e "s/LIBBTRFS0/libbtrfs0/g" \
              -e "s/LIBGPGME11/libgpgme11/g" \
              -e "s/LIBUV1/libuv1/g"
          fi

          if [ "${PKGOS}" = "debian-13" ]; then
            sed -i debian/control \
              -e "s/LIBFUSE3/libfuse3-4/g"
          else
            sed -i debian/control \
              -e "s/LIBFUSE3/libfuse3-3/g"
          fi

          dch --package incus --create -D ${CODENAME} -M -m "Automated Incus stable build" -v 1:$(echo ${INCUS_TAG} | sed -e "s/v//" -e "s/.0$//")-$(echo ${PKGOS} | sed "s/-//g")-$(date -u +%Y%m%d%H%M) --force-distribution
          dpkg-buildpackage -b

          cd ..
          mkdir out
          mv incus_* out/
          mv incus-base_* out/
          mv incus-client_* out/
          mv incus-extra_* out/
          mv incus-ui-canonical_* out/

      - name: Upload resulting build
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: out/*
